package com.spring.model1;

import java.math.BigDecimal;

public class FidTempTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.FID_TEMP_TABLE.FID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private BigDecimal fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.FID_TEMP_TABLE.FID
     *
     * @return the value of ONLINEQC.FID_TEMP_TABLE.FID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public BigDecimal getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.FID_TEMP_TABLE.FID
     *
     * @param fid the value for ONLINEQC.FID_TEMP_TABLE.FID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setFid(BigDecimal fid) {
        this.fid = fid;
    }
}