package com.spring.model1;

import java.math.BigDecimal;

public class IdxCalcThsTempTab {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.OBJECTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String objectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String objecttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.TARGETVALUE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private BigDecimal targetvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.THRESHOLDVALUE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private BigDecimal thresholdvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.OBJECTID
     *
     * @return the value of ONLINEQC.IDX_CALC_THS_TEMP_TAB.OBJECTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getObjectid() {
        return objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.OBJECTID
     *
     * @param objectid the value for ONLINEQC.IDX_CALC_THS_TEMP_TAB.OBJECTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setObjectid(String objectid) {
        this.objectid = objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.OBJECTTYPE
     *
     * @return the value of ONLINEQC.IDX_CALC_THS_TEMP_TAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getObjecttype() {
        return objecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.OBJECTTYPE
     *
     * @param objecttype the value for ONLINEQC.IDX_CALC_THS_TEMP_TAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setObjecttype(String objecttype) {
        this.objecttype = objecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.TARGETVALUE
     *
     * @return the value of ONLINEQC.IDX_CALC_THS_TEMP_TAB.TARGETVALUE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public BigDecimal getTargetvalue() {
        return targetvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.TARGETVALUE
     *
     * @param targetvalue the value for ONLINEQC.IDX_CALC_THS_TEMP_TAB.TARGETVALUE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTargetvalue(BigDecimal targetvalue) {
        this.targetvalue = targetvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.THRESHOLDVALUE
     *
     * @return the value of ONLINEQC.IDX_CALC_THS_TEMP_TAB.THRESHOLDVALUE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public BigDecimal getThresholdvalue() {
        return thresholdvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.IDX_CALC_THS_TEMP_TAB.THRESHOLDVALUE
     *
     * @param thresholdvalue the value for ONLINEQC.IDX_CALC_THS_TEMP_TAB.THRESHOLDVALUE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setThresholdvalue(BigDecimal thresholdvalue) {
        this.thresholdvalue = thresholdvalue;
    }
}