package com.spring.model1;

import java.math.BigDecimal;
import java.util.Date;

public class QcCallsessionstab extends QcCallsessionstabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLSESSIONKEY
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String callsessionkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.AGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String agentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String callid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLFROM
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String callfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLTO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String callto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Date calltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.TALKTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Long talktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.RECFILEPATH
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String recfilepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.PROCESSSTATUS
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String processstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Date lastchangetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.LIMITTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Date limittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.AFMATCHRATE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private BigDecimal afmatchrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.LMCOUNT
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Long lmcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_CALLSESSIONSTAB.JNTXTEXISTS
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String jntxtexists;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLSESSIONKEY
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.CALLSESSIONKEY
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getCallsessionkey() {
        return callsessionkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLSESSIONKEY
     *
     * @param callsessionkey the value for ONLINEQC.QC_CALLSESSIONSTAB.CALLSESSIONKEY
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setCallsessionkey(String callsessionkey) {
        this.callsessionkey = callsessionkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.AGENTID
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.AGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.AGENTID
     *
     * @param agentid the value for ONLINEQC.QC_CALLSESSIONSTAB.AGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLID
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.CALLID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getCallid() {
        return callid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLID
     *
     * @param callid the value for ONLINEQC.QC_CALLSESSIONSTAB.CALLID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setCallid(String callid) {
        this.callid = callid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLFROM
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.CALLFROM
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getCallfrom() {
        return callfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLFROM
     *
     * @param callfrom the value for ONLINEQC.QC_CALLSESSIONSTAB.CALLFROM
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setCallfrom(String callfrom) {
        this.callfrom = callfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLTO
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.CALLTO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getCallto() {
        return callto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLTO
     *
     * @param callto the value for ONLINEQC.QC_CALLSESSIONSTAB.CALLTO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setCallto(String callto) {
        this.callto = callto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLTIME
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.CALLTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Date getCalltime() {
        return calltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.CALLTIME
     *
     * @param calltime the value for ONLINEQC.QC_CALLSESSIONSTAB.CALLTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setCalltime(Date calltime) {
        this.calltime = calltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.TALKTIME
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.TALKTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Long getTalktime() {
        return talktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.TALKTIME
     *
     * @param talktime the value for ONLINEQC.QC_CALLSESSIONSTAB.TALKTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTalktime(Long talktime) {
        this.talktime = talktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.RECFILEPATH
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.RECFILEPATH
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getRecfilepath() {
        return recfilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.RECFILEPATH
     *
     * @param recfilepath the value for ONLINEQC.QC_CALLSESSIONSTAB.RECFILEPATH
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setRecfilepath(String recfilepath) {
        this.recfilepath = recfilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.PROCESSSTATUS
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.PROCESSSTATUS
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getProcessstatus() {
        return processstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.PROCESSSTATUS
     *
     * @param processstatus the value for ONLINEQC.QC_CALLSESSIONSTAB.PROCESSSTATUS
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setProcessstatus(String processstatus) {
        this.processstatus = processstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.LASTCHANGETIME
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Date getLastchangetime() {
        return lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.LASTCHANGETIME
     *
     * @param lastchangetime the value for ONLINEQC.QC_CALLSESSIONSTAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setLastchangetime(Date lastchangetime) {
        this.lastchangetime = lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.LIMITTIME
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.LIMITTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Date getLimittime() {
        return limittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.LIMITTIME
     *
     * @param limittime the value for ONLINEQC.QC_CALLSESSIONSTAB.LIMITTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setLimittime(Date limittime) {
        this.limittime = limittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.AFMATCHRATE
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.AFMATCHRATE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public BigDecimal getAfmatchrate() {
        return afmatchrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.AFMATCHRATE
     *
     * @param afmatchrate the value for ONLINEQC.QC_CALLSESSIONSTAB.AFMATCHRATE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setAfmatchrate(BigDecimal afmatchrate) {
        this.afmatchrate = afmatchrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.LMCOUNT
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.LMCOUNT
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Long getLmcount() {
        return lmcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.LMCOUNT
     *
     * @param lmcount the value for ONLINEQC.QC_CALLSESSIONSTAB.LMCOUNT
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setLmcount(Long lmcount) {
        this.lmcount = lmcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.JNTXTEXISTS
     *
     * @return the value of ONLINEQC.QC_CALLSESSIONSTAB.JNTXTEXISTS
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getJntxtexists() {
        return jntxtexists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_CALLSESSIONSTAB.JNTXTEXISTS
     *
     * @param jntxtexists the value for ONLINEQC.QC_CALLSESSIONSTAB.JNTXTEXISTS
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setJntxtexists(String jntxtexists) {
        this.jntxtexists = jntxtexists;
    }
}