package com.spring.model1;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QcOrgchangetabExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public QcOrgchangetabExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Short value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Short value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Short value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Short value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Short value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Short value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Short> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Short> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Short value1, Short value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Short value1, Short value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTenantidIsNull() {
            addCriterion("TENANTID is null");
            return (Criteria) this;
        }

        public Criteria andTenantidIsNotNull() {
            addCriterion("TENANTID is not null");
            return (Criteria) this;
        }

        public Criteria andTenantidEqualTo(String value) {
            addCriterion("TENANTID =", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotEqualTo(String value) {
            addCriterion("TENANTID <>", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidGreaterThan(String value) {
            addCriterion("TENANTID >", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidGreaterThanOrEqualTo(String value) {
            addCriterion("TENANTID >=", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidLessThan(String value) {
            addCriterion("TENANTID <", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidLessThanOrEqualTo(String value) {
            addCriterion("TENANTID <=", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidLike(String value) {
            addCriterion("TENANTID like", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotLike(String value) {
            addCriterion("TENANTID not like", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidIn(List<String> values) {
            addCriterion("TENANTID in", values, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotIn(List<String> values) {
            addCriterion("TENANTID not in", values, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidBetween(String value1, String value2) {
            addCriterion("TENANTID between", value1, value2, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotBetween(String value1, String value2) {
            addCriterion("TENANTID not between", value1, value2, "tenantid");
            return (Criteria) this;
        }

        public Criteria andMgridIsNull() {
            addCriterion("MGRID is null");
            return (Criteria) this;
        }

        public Criteria andMgridIsNotNull() {
            addCriterion("MGRID is not null");
            return (Criteria) this;
        }

        public Criteria andMgridEqualTo(String value) {
            addCriterion("MGRID =", value, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridNotEqualTo(String value) {
            addCriterion("MGRID <>", value, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridGreaterThan(String value) {
            addCriterion("MGRID >", value, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridGreaterThanOrEqualTo(String value) {
            addCriterion("MGRID >=", value, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridLessThan(String value) {
            addCriterion("MGRID <", value, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridLessThanOrEqualTo(String value) {
            addCriterion("MGRID <=", value, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridLike(String value) {
            addCriterion("MGRID like", value, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridNotLike(String value) {
            addCriterion("MGRID not like", value, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridIn(List<String> values) {
            addCriterion("MGRID in", values, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridNotIn(List<String> values) {
            addCriterion("MGRID not in", values, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridBetween(String value1, String value2) {
            addCriterion("MGRID between", value1, value2, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgridNotBetween(String value1, String value2) {
            addCriterion("MGRID not between", value1, value2, "mgrid");
            return (Criteria) this;
        }

        public Criteria andMgrnameIsNull() {
            addCriterion("MGRNAME is null");
            return (Criteria) this;
        }

        public Criteria andMgrnameIsNotNull() {
            addCriterion("MGRNAME is not null");
            return (Criteria) this;
        }

        public Criteria andMgrnameEqualTo(Object value) {
            addCriterion("MGRNAME =", value, "mgrname");
            return (Criteria) this;
        }

        public Criteria andMgrnameNotEqualTo(Object value) {
            addCriterion("MGRNAME <>", value, "mgrname");
            return (Criteria) this;
        }

        public Criteria andMgrnameGreaterThan(Object value) {
            addCriterion("MGRNAME >", value, "mgrname");
            return (Criteria) this;
        }

        public Criteria andMgrnameGreaterThanOrEqualTo(Object value) {
            addCriterion("MGRNAME >=", value, "mgrname");
            return (Criteria) this;
        }

        public Criteria andMgrnameLessThan(Object value) {
            addCriterion("MGRNAME <", value, "mgrname");
            return (Criteria) this;
        }

        public Criteria andMgrnameLessThanOrEqualTo(Object value) {
            addCriterion("MGRNAME <=", value, "mgrname");
            return (Criteria) this;
        }

        public Criteria andMgrnameIn(List<Object> values) {
            addCriterion("MGRNAME in", values, "mgrname");
            return (Criteria) this;
        }

        public Criteria andMgrnameNotIn(List<Object> values) {
            addCriterion("MGRNAME not in", values, "mgrname");
            return (Criteria) this;
        }

        public Criteria andMgrnameBetween(Object value1, Object value2) {
            addCriterion("MGRNAME between", value1, value2, "mgrname");
            return (Criteria) this;
        }

        public Criteria andMgrnameNotBetween(Object value1, Object value2) {
            addCriterion("MGRNAME not between", value1, value2, "mgrname");
            return (Criteria) this;
        }

        public Criteria andMgrpositionIsNull() {
            addCriterion("MGRPOSITION is null");
            return (Criteria) this;
        }

        public Criteria andMgrpositionIsNotNull() {
            addCriterion("MGRPOSITION is not null");
            return (Criteria) this;
        }

        public Criteria andMgrpositionEqualTo(String value) {
            addCriterion("MGRPOSITION =", value, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionNotEqualTo(String value) {
            addCriterion("MGRPOSITION <>", value, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionGreaterThan(String value) {
            addCriterion("MGRPOSITION >", value, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionGreaterThanOrEqualTo(String value) {
            addCriterion("MGRPOSITION >=", value, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionLessThan(String value) {
            addCriterion("MGRPOSITION <", value, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionLessThanOrEqualTo(String value) {
            addCriterion("MGRPOSITION <=", value, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionLike(String value) {
            addCriterion("MGRPOSITION like", value, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionNotLike(String value) {
            addCriterion("MGRPOSITION not like", value, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionIn(List<String> values) {
            addCriterion("MGRPOSITION in", values, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionNotIn(List<String> values) {
            addCriterion("MGRPOSITION not in", values, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionBetween(String value1, String value2) {
            addCriterion("MGRPOSITION between", value1, value2, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andMgrpositionNotBetween(String value1, String value2) {
            addCriterion("MGRPOSITION not between", value1, value2, "mgrposition");
            return (Criteria) this;
        }

        public Criteria andOrgfromidIsNull() {
            addCriterion("ORGFROMID is null");
            return (Criteria) this;
        }

        public Criteria andOrgfromidIsNotNull() {
            addCriterion("ORGFROMID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgfromidEqualTo(Short value) {
            addCriterion("ORGFROMID =", value, "orgfromid");
            return (Criteria) this;
        }

        public Criteria andOrgfromidNotEqualTo(Short value) {
            addCriterion("ORGFROMID <>", value, "orgfromid");
            return (Criteria) this;
        }

        public Criteria andOrgfromidGreaterThan(Short value) {
            addCriterion("ORGFROMID >", value, "orgfromid");
            return (Criteria) this;
        }

        public Criteria andOrgfromidGreaterThanOrEqualTo(Short value) {
            addCriterion("ORGFROMID >=", value, "orgfromid");
            return (Criteria) this;
        }

        public Criteria andOrgfromidLessThan(Short value) {
            addCriterion("ORGFROMID <", value, "orgfromid");
            return (Criteria) this;
        }

        public Criteria andOrgfromidLessThanOrEqualTo(Short value) {
            addCriterion("ORGFROMID <=", value, "orgfromid");
            return (Criteria) this;
        }

        public Criteria andOrgfromidIn(List<Short> values) {
            addCriterion("ORGFROMID in", values, "orgfromid");
            return (Criteria) this;
        }

        public Criteria andOrgfromidNotIn(List<Short> values) {
            addCriterion("ORGFROMID not in", values, "orgfromid");
            return (Criteria) this;
        }

        public Criteria andOrgfromidBetween(Short value1, Short value2) {
            addCriterion("ORGFROMID between", value1, value2, "orgfromid");
            return (Criteria) this;
        }

        public Criteria andOrgfromidNotBetween(Short value1, Short value2) {
            addCriterion("ORGFROMID not between", value1, value2, "orgfromid");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameIsNull() {
            addCriterion("ORGFROMNAME is null");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameIsNotNull() {
            addCriterion("ORGFROMNAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameEqualTo(String value) {
            addCriterion("ORGFROMNAME =", value, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameNotEqualTo(String value) {
            addCriterion("ORGFROMNAME <>", value, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameGreaterThan(String value) {
            addCriterion("ORGFROMNAME >", value, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameGreaterThanOrEqualTo(String value) {
            addCriterion("ORGFROMNAME >=", value, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameLessThan(String value) {
            addCriterion("ORGFROMNAME <", value, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameLessThanOrEqualTo(String value) {
            addCriterion("ORGFROMNAME <=", value, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameLike(String value) {
            addCriterion("ORGFROMNAME like", value, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameNotLike(String value) {
            addCriterion("ORGFROMNAME not like", value, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameIn(List<String> values) {
            addCriterion("ORGFROMNAME in", values, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameNotIn(List<String> values) {
            addCriterion("ORGFROMNAME not in", values, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameBetween(String value1, String value2) {
            addCriterion("ORGFROMNAME between", value1, value2, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgfromnameNotBetween(String value1, String value2) {
            addCriterion("ORGFROMNAME not between", value1, value2, "orgfromname");
            return (Criteria) this;
        }

        public Criteria andOrgtoidIsNull() {
            addCriterion("ORGTOID is null");
            return (Criteria) this;
        }

        public Criteria andOrgtoidIsNotNull() {
            addCriterion("ORGTOID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgtoidEqualTo(Short value) {
            addCriterion("ORGTOID =", value, "orgtoid");
            return (Criteria) this;
        }

        public Criteria andOrgtoidNotEqualTo(Short value) {
            addCriterion("ORGTOID <>", value, "orgtoid");
            return (Criteria) this;
        }

        public Criteria andOrgtoidGreaterThan(Short value) {
            addCriterion("ORGTOID >", value, "orgtoid");
            return (Criteria) this;
        }

        public Criteria andOrgtoidGreaterThanOrEqualTo(Short value) {
            addCriterion("ORGTOID >=", value, "orgtoid");
            return (Criteria) this;
        }

        public Criteria andOrgtoidLessThan(Short value) {
            addCriterion("ORGTOID <", value, "orgtoid");
            return (Criteria) this;
        }

        public Criteria andOrgtoidLessThanOrEqualTo(Short value) {
            addCriterion("ORGTOID <=", value, "orgtoid");
            return (Criteria) this;
        }

        public Criteria andOrgtoidIn(List<Short> values) {
            addCriterion("ORGTOID in", values, "orgtoid");
            return (Criteria) this;
        }

        public Criteria andOrgtoidNotIn(List<Short> values) {
            addCriterion("ORGTOID not in", values, "orgtoid");
            return (Criteria) this;
        }

        public Criteria andOrgtoidBetween(Short value1, Short value2) {
            addCriterion("ORGTOID between", value1, value2, "orgtoid");
            return (Criteria) this;
        }

        public Criteria andOrgtoidNotBetween(Short value1, Short value2) {
            addCriterion("ORGTOID not between", value1, value2, "orgtoid");
            return (Criteria) this;
        }

        public Criteria andOrgtonameIsNull() {
            addCriterion("ORGTONAME is null");
            return (Criteria) this;
        }

        public Criteria andOrgtonameIsNotNull() {
            addCriterion("ORGTONAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrgtonameEqualTo(String value) {
            addCriterion("ORGTONAME =", value, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameNotEqualTo(String value) {
            addCriterion("ORGTONAME <>", value, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameGreaterThan(String value) {
            addCriterion("ORGTONAME >", value, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameGreaterThanOrEqualTo(String value) {
            addCriterion("ORGTONAME >=", value, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameLessThan(String value) {
            addCriterion("ORGTONAME <", value, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameLessThanOrEqualTo(String value) {
            addCriterion("ORGTONAME <=", value, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameLike(String value) {
            addCriterion("ORGTONAME like", value, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameNotLike(String value) {
            addCriterion("ORGTONAME not like", value, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameIn(List<String> values) {
            addCriterion("ORGTONAME in", values, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameNotIn(List<String> values) {
            addCriterion("ORGTONAME not in", values, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameBetween(String value1, String value2) {
            addCriterion("ORGTONAME between", value1, value2, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andOrgtonameNotBetween(String value1, String value2) {
            addCriterion("ORGTONAME not between", value1, value2, "orgtoname");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeIsNull() {
            addCriterion("SCHFROMTIME is null");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeIsNotNull() {
            addCriterion("SCHFROMTIME is not null");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeEqualTo(Date value) {
            addCriterion("SCHFROMTIME =", value, "schfromtime");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeNotEqualTo(Date value) {
            addCriterion("SCHFROMTIME <>", value, "schfromtime");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeGreaterThan(Date value) {
            addCriterion("SCHFROMTIME >", value, "schfromtime");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SCHFROMTIME >=", value, "schfromtime");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeLessThan(Date value) {
            addCriterion("SCHFROMTIME <", value, "schfromtime");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeLessThanOrEqualTo(Date value) {
            addCriterion("SCHFROMTIME <=", value, "schfromtime");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeIn(List<Date> values) {
            addCriterion("SCHFROMTIME in", values, "schfromtime");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeNotIn(List<Date> values) {
            addCriterion("SCHFROMTIME not in", values, "schfromtime");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeBetween(Date value1, Date value2) {
            addCriterion("SCHFROMTIME between", value1, value2, "schfromtime");
            return (Criteria) this;
        }

        public Criteria andSchfromtimeNotBetween(Date value1, Date value2) {
            addCriterion("SCHFROMTIME not between", value1, value2, "schfromtime");
            return (Criteria) this;
        }

        public Criteria andSchtotimeIsNull() {
            addCriterion("SCHTOTIME is null");
            return (Criteria) this;
        }

        public Criteria andSchtotimeIsNotNull() {
            addCriterion("SCHTOTIME is not null");
            return (Criteria) this;
        }

        public Criteria andSchtotimeEqualTo(Date value) {
            addCriterion("SCHTOTIME =", value, "schtotime");
            return (Criteria) this;
        }

        public Criteria andSchtotimeNotEqualTo(Date value) {
            addCriterion("SCHTOTIME <>", value, "schtotime");
            return (Criteria) this;
        }

        public Criteria andSchtotimeGreaterThan(Date value) {
            addCriterion("SCHTOTIME >", value, "schtotime");
            return (Criteria) this;
        }

        public Criteria andSchtotimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SCHTOTIME >=", value, "schtotime");
            return (Criteria) this;
        }

        public Criteria andSchtotimeLessThan(Date value) {
            addCriterion("SCHTOTIME <", value, "schtotime");
            return (Criteria) this;
        }

        public Criteria andSchtotimeLessThanOrEqualTo(Date value) {
            addCriterion("SCHTOTIME <=", value, "schtotime");
            return (Criteria) this;
        }

        public Criteria andSchtotimeIn(List<Date> values) {
            addCriterion("SCHTOTIME in", values, "schtotime");
            return (Criteria) this;
        }

        public Criteria andSchtotimeNotIn(List<Date> values) {
            addCriterion("SCHTOTIME not in", values, "schtotime");
            return (Criteria) this;
        }

        public Criteria andSchtotimeBetween(Date value1, Date value2) {
            addCriterion("SCHTOTIME between", value1, value2, "schtotime");
            return (Criteria) this;
        }

        public Criteria andSchtotimeNotBetween(Date value1, Date value2) {
            addCriterion("SCHTOTIME not between", value1, value2, "schtotime");
            return (Criteria) this;
        }

        public Criteria andActendtimeIsNull() {
            addCriterion("ACTENDTIME is null");
            return (Criteria) this;
        }

        public Criteria andActendtimeIsNotNull() {
            addCriterion("ACTENDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andActendtimeEqualTo(Date value) {
            addCriterion("ACTENDTIME =", value, "actendtime");
            return (Criteria) this;
        }

        public Criteria andActendtimeNotEqualTo(Date value) {
            addCriterion("ACTENDTIME <>", value, "actendtime");
            return (Criteria) this;
        }

        public Criteria andActendtimeGreaterThan(Date value) {
            addCriterion("ACTENDTIME >", value, "actendtime");
            return (Criteria) this;
        }

        public Criteria andActendtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ACTENDTIME >=", value, "actendtime");
            return (Criteria) this;
        }

        public Criteria andActendtimeLessThan(Date value) {
            addCriterion("ACTENDTIME <", value, "actendtime");
            return (Criteria) this;
        }

        public Criteria andActendtimeLessThanOrEqualTo(Date value) {
            addCriterion("ACTENDTIME <=", value, "actendtime");
            return (Criteria) this;
        }

        public Criteria andActendtimeIn(List<Date> values) {
            addCriterion("ACTENDTIME in", values, "actendtime");
            return (Criteria) this;
        }

        public Criteria andActendtimeNotIn(List<Date> values) {
            addCriterion("ACTENDTIME not in", values, "actendtime");
            return (Criteria) this;
        }

        public Criteria andActendtimeBetween(Date value1, Date value2) {
            addCriterion("ACTENDTIME between", value1, value2, "actendtime");
            return (Criteria) this;
        }

        public Criteria andActendtimeNotBetween(Date value1, Date value2) {
            addCriterion("ACTENDTIME not between", value1, value2, "actendtime");
            return (Criteria) this;
        }

        public Criteria andApplicantidIsNull() {
            addCriterion("APPLICANTID is null");
            return (Criteria) this;
        }

        public Criteria andApplicantidIsNotNull() {
            addCriterion("APPLICANTID is not null");
            return (Criteria) this;
        }

        public Criteria andApplicantidEqualTo(Short value) {
            addCriterion("APPLICANTID =", value, "applicantid");
            return (Criteria) this;
        }

        public Criteria andApplicantidNotEqualTo(Short value) {
            addCriterion("APPLICANTID <>", value, "applicantid");
            return (Criteria) this;
        }

        public Criteria andApplicantidGreaterThan(Short value) {
            addCriterion("APPLICANTID >", value, "applicantid");
            return (Criteria) this;
        }

        public Criteria andApplicantidGreaterThanOrEqualTo(Short value) {
            addCriterion("APPLICANTID >=", value, "applicantid");
            return (Criteria) this;
        }

        public Criteria andApplicantidLessThan(Short value) {
            addCriterion("APPLICANTID <", value, "applicantid");
            return (Criteria) this;
        }

        public Criteria andApplicantidLessThanOrEqualTo(Short value) {
            addCriterion("APPLICANTID <=", value, "applicantid");
            return (Criteria) this;
        }

        public Criteria andApplicantidIn(List<Short> values) {
            addCriterion("APPLICANTID in", values, "applicantid");
            return (Criteria) this;
        }

        public Criteria andApplicantidNotIn(List<Short> values) {
            addCriterion("APPLICANTID not in", values, "applicantid");
            return (Criteria) this;
        }

        public Criteria andApplicantidBetween(Short value1, Short value2) {
            addCriterion("APPLICANTID between", value1, value2, "applicantid");
            return (Criteria) this;
        }

        public Criteria andApplicantidNotBetween(Short value1, Short value2) {
            addCriterion("APPLICANTID not between", value1, value2, "applicantid");
            return (Criteria) this;
        }

        public Criteria andApplicantnameIsNull() {
            addCriterion("APPLICANTNAME is null");
            return (Criteria) this;
        }

        public Criteria andApplicantnameIsNotNull() {
            addCriterion("APPLICANTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andApplicantnameEqualTo(String value) {
            addCriterion("APPLICANTNAME =", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameNotEqualTo(String value) {
            addCriterion("APPLICANTNAME <>", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameGreaterThan(String value) {
            addCriterion("APPLICANTNAME >", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameGreaterThanOrEqualTo(String value) {
            addCriterion("APPLICANTNAME >=", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameLessThan(String value) {
            addCriterion("APPLICANTNAME <", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameLessThanOrEqualTo(String value) {
            addCriterion("APPLICANTNAME <=", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameLike(String value) {
            addCriterion("APPLICANTNAME like", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameNotLike(String value) {
            addCriterion("APPLICANTNAME not like", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameIn(List<String> values) {
            addCriterion("APPLICANTNAME in", values, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameNotIn(List<String> values) {
            addCriterion("APPLICANTNAME not in", values, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameBetween(String value1, String value2) {
            addCriterion("APPLICANTNAME between", value1, value2, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameNotBetween(String value1, String value2) {
            addCriterion("APPLICANTNAME not between", value1, value2, "applicantname");
            return (Criteria) this;
        }

        public Criteria andExecutoridIsNull() {
            addCriterion("EXECUTORID is null");
            return (Criteria) this;
        }

        public Criteria andExecutoridIsNotNull() {
            addCriterion("EXECUTORID is not null");
            return (Criteria) this;
        }

        public Criteria andExecutoridEqualTo(Short value) {
            addCriterion("EXECUTORID =", value, "executorid");
            return (Criteria) this;
        }

        public Criteria andExecutoridNotEqualTo(Short value) {
            addCriterion("EXECUTORID <>", value, "executorid");
            return (Criteria) this;
        }

        public Criteria andExecutoridGreaterThan(Short value) {
            addCriterion("EXECUTORID >", value, "executorid");
            return (Criteria) this;
        }

        public Criteria andExecutoridGreaterThanOrEqualTo(Short value) {
            addCriterion("EXECUTORID >=", value, "executorid");
            return (Criteria) this;
        }

        public Criteria andExecutoridLessThan(Short value) {
            addCriterion("EXECUTORID <", value, "executorid");
            return (Criteria) this;
        }

        public Criteria andExecutoridLessThanOrEqualTo(Short value) {
            addCriterion("EXECUTORID <=", value, "executorid");
            return (Criteria) this;
        }

        public Criteria andExecutoridIn(List<Short> values) {
            addCriterion("EXECUTORID in", values, "executorid");
            return (Criteria) this;
        }

        public Criteria andExecutoridNotIn(List<Short> values) {
            addCriterion("EXECUTORID not in", values, "executorid");
            return (Criteria) this;
        }

        public Criteria andExecutoridBetween(Short value1, Short value2) {
            addCriterion("EXECUTORID between", value1, value2, "executorid");
            return (Criteria) this;
        }

        public Criteria andExecutoridNotBetween(Short value1, Short value2) {
            addCriterion("EXECUTORID not between", value1, value2, "executorid");
            return (Criteria) this;
        }

        public Criteria andExecutornameIsNull() {
            addCriterion("EXECUTORNAME is null");
            return (Criteria) this;
        }

        public Criteria andExecutornameIsNotNull() {
            addCriterion("EXECUTORNAME is not null");
            return (Criteria) this;
        }

        public Criteria andExecutornameEqualTo(String value) {
            addCriterion("EXECUTORNAME =", value, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameNotEqualTo(String value) {
            addCriterion("EXECUTORNAME <>", value, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameGreaterThan(String value) {
            addCriterion("EXECUTORNAME >", value, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameGreaterThanOrEqualTo(String value) {
            addCriterion("EXECUTORNAME >=", value, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameLessThan(String value) {
            addCriterion("EXECUTORNAME <", value, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameLessThanOrEqualTo(String value) {
            addCriterion("EXECUTORNAME <=", value, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameLike(String value) {
            addCriterion("EXECUTORNAME like", value, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameNotLike(String value) {
            addCriterion("EXECUTORNAME not like", value, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameIn(List<String> values) {
            addCriterion("EXECUTORNAME in", values, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameNotIn(List<String> values) {
            addCriterion("EXECUTORNAME not in", values, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameBetween(String value1, String value2) {
            addCriterion("EXECUTORNAME between", value1, value2, "executorname");
            return (Criteria) this;
        }

        public Criteria andExecutornameNotBetween(String value1, String value2) {
            addCriterion("EXECUTORNAME not between", value1, value2, "executorname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 08 16:40:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ONLINEQC.QC_ORGCHANGETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}