package com.spring.model1;

import java.util.Date;

public class QcPopupinfo extends QcPopupinfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.TARGETTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String targettype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.POPUPACTIONTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Date popupactiontime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.POPUPCREATETIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Date popupcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.POPUPTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String popuptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.POPUPLEVEL
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String popuplevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.BUSITYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String busitype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.TIPSCOLOR
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String tipscolor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.CONTENTTEMPLATE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object contenttemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.TTROLE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String ttrole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.AGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String agentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.AGENTEMID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String agentemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.AGENTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String agentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.TTCID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Long ttcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.TACID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Long tacid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.TTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Long ttid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.CSID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Long csid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.CALLKEY
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String callkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.CALLFROM
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String callfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.CALLTO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String callto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.ORGTEAMID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String orgteamid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.ORGTEAMNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object orgteamname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.ORGTEAMAGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String orgteamagentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.ORGTEAMAGENTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String orgteamagentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.NOWTEAMID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String nowteamid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.NOWTEAMNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object nowteamname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.NOWTEAMAGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String nowteamagentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.NOWTEAMAGENTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String nowteamagentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C1
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C2
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C3
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C4
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C5
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C6
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C7
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C8
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C9
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C10
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C11
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C12
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C13
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C14
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C15
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C16
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C17
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C18
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C19
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C20
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C21
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C22
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C23
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C24
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C25
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c25;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C26
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c26;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C27
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c27;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C28
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c28;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_POPUPINFO.C29
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Object c29;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.TARGETTYPE
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.TARGETTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getTargettype() {
        return targettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.TARGETTYPE
     *
     * @param targettype the value for ONLINEQC.QC_POPUPINFO.TARGETTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTargettype(String targettype) {
        this.targettype = targettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.POPUPACTIONTIME
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.POPUPACTIONTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Date getPopupactiontime() {
        return popupactiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.POPUPACTIONTIME
     *
     * @param popupactiontime the value for ONLINEQC.QC_POPUPINFO.POPUPACTIONTIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setPopupactiontime(Date popupactiontime) {
        this.popupactiontime = popupactiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.POPUPCREATETIME
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.POPUPCREATETIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Date getPopupcreatetime() {
        return popupcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.POPUPCREATETIME
     *
     * @param popupcreatetime the value for ONLINEQC.QC_POPUPINFO.POPUPCREATETIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setPopupcreatetime(Date popupcreatetime) {
        this.popupcreatetime = popupcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.POPUPTYPE
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.POPUPTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getPopuptype() {
        return popuptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.POPUPTYPE
     *
     * @param popuptype the value for ONLINEQC.QC_POPUPINFO.POPUPTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setPopuptype(String popuptype) {
        this.popuptype = popuptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.POPUPLEVEL
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.POPUPLEVEL
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getPopuplevel() {
        return popuplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.POPUPLEVEL
     *
     * @param popuplevel the value for ONLINEQC.QC_POPUPINFO.POPUPLEVEL
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setPopuplevel(String popuplevel) {
        this.popuplevel = popuplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.BUSITYPE
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.BUSITYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getBusitype() {
        return busitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.BUSITYPE
     *
     * @param busitype the value for ONLINEQC.QC_POPUPINFO.BUSITYPE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setBusitype(String busitype) {
        this.busitype = busitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.TIPSCOLOR
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.TIPSCOLOR
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getTipscolor() {
        return tipscolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.TIPSCOLOR
     *
     * @param tipscolor the value for ONLINEQC.QC_POPUPINFO.TIPSCOLOR
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTipscolor(String tipscolor) {
        this.tipscolor = tipscolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.CONTENTTEMPLATE
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.CONTENTTEMPLATE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getContenttemplate() {
        return contenttemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.CONTENTTEMPLATE
     *
     * @param contenttemplate the value for ONLINEQC.QC_POPUPINFO.CONTENTTEMPLATE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setContenttemplate(Object contenttemplate) {
        this.contenttemplate = contenttemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.TTROLE
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.TTROLE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getTtrole() {
        return ttrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.TTROLE
     *
     * @param ttrole the value for ONLINEQC.QC_POPUPINFO.TTROLE
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTtrole(String ttrole) {
        this.ttrole = ttrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.AGENTID
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.AGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.AGENTID
     *
     * @param agentid the value for ONLINEQC.QC_POPUPINFO.AGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.AGENTEMID
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.AGENTEMID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getAgentemid() {
        return agentemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.AGENTEMID
     *
     * @param agentemid the value for ONLINEQC.QC_POPUPINFO.AGENTEMID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setAgentemid(String agentemid) {
        this.agentemid = agentemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.AGENTNAME
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.AGENTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getAgentname() {
        return agentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.AGENTNAME
     *
     * @param agentname the value for ONLINEQC.QC_POPUPINFO.AGENTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.TTCID
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.TTCID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Long getTtcid() {
        return ttcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.TTCID
     *
     * @param ttcid the value for ONLINEQC.QC_POPUPINFO.TTCID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTtcid(Long ttcid) {
        this.ttcid = ttcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.TACID
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.TACID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Long getTacid() {
        return tacid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.TACID
     *
     * @param tacid the value for ONLINEQC.QC_POPUPINFO.TACID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTacid(Long tacid) {
        this.tacid = tacid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.TTID
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.TTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Long getTtid() {
        return ttid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.TTID
     *
     * @param ttid the value for ONLINEQC.QC_POPUPINFO.TTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTtid(Long ttid) {
        this.ttid = ttid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.CSID
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.CSID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Long getCsid() {
        return csid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.CSID
     *
     * @param csid the value for ONLINEQC.QC_POPUPINFO.CSID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setCsid(Long csid) {
        this.csid = csid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.CALLKEY
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.CALLKEY
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getCallkey() {
        return callkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.CALLKEY
     *
     * @param callkey the value for ONLINEQC.QC_POPUPINFO.CALLKEY
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setCallkey(String callkey) {
        this.callkey = callkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.CALLFROM
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.CALLFROM
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getCallfrom() {
        return callfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.CALLFROM
     *
     * @param callfrom the value for ONLINEQC.QC_POPUPINFO.CALLFROM
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setCallfrom(String callfrom) {
        this.callfrom = callfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.CALLTO
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.CALLTO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getCallto() {
        return callto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.CALLTO
     *
     * @param callto the value for ONLINEQC.QC_POPUPINFO.CALLTO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setCallto(String callto) {
        this.callto = callto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.ORGTEAMID
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.ORGTEAMID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getOrgteamid() {
        return orgteamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.ORGTEAMID
     *
     * @param orgteamid the value for ONLINEQC.QC_POPUPINFO.ORGTEAMID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setOrgteamid(String orgteamid) {
        this.orgteamid = orgteamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.ORGTEAMNAME
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.ORGTEAMNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getOrgteamname() {
        return orgteamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.ORGTEAMNAME
     *
     * @param orgteamname the value for ONLINEQC.QC_POPUPINFO.ORGTEAMNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setOrgteamname(Object orgteamname) {
        this.orgteamname = orgteamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.ORGTEAMAGENTID
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.ORGTEAMAGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getOrgteamagentid() {
        return orgteamagentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.ORGTEAMAGENTID
     *
     * @param orgteamagentid the value for ONLINEQC.QC_POPUPINFO.ORGTEAMAGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setOrgteamagentid(String orgteamagentid) {
        this.orgteamagentid = orgteamagentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.ORGTEAMAGENTNAME
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.ORGTEAMAGENTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getOrgteamagentname() {
        return orgteamagentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.ORGTEAMAGENTNAME
     *
     * @param orgteamagentname the value for ONLINEQC.QC_POPUPINFO.ORGTEAMAGENTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setOrgteamagentname(String orgteamagentname) {
        this.orgteamagentname = orgteamagentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.NOWTEAMID
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.NOWTEAMID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getNowteamid() {
        return nowteamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.NOWTEAMID
     *
     * @param nowteamid the value for ONLINEQC.QC_POPUPINFO.NOWTEAMID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setNowteamid(String nowteamid) {
        this.nowteamid = nowteamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.NOWTEAMNAME
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.NOWTEAMNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getNowteamname() {
        return nowteamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.NOWTEAMNAME
     *
     * @param nowteamname the value for ONLINEQC.QC_POPUPINFO.NOWTEAMNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setNowteamname(Object nowteamname) {
        this.nowteamname = nowteamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.NOWTEAMAGENTID
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.NOWTEAMAGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getNowteamagentid() {
        return nowteamagentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.NOWTEAMAGENTID
     *
     * @param nowteamagentid the value for ONLINEQC.QC_POPUPINFO.NOWTEAMAGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setNowteamagentid(String nowteamagentid) {
        this.nowteamagentid = nowteamagentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.NOWTEAMAGENTNAME
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.NOWTEAMAGENTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getNowteamagentname() {
        return nowteamagentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.NOWTEAMAGENTNAME
     *
     * @param nowteamagentname the value for ONLINEQC.QC_POPUPINFO.NOWTEAMAGENTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setNowteamagentname(String nowteamagentname) {
        this.nowteamagentname = nowteamagentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C0
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC0() {
        return c0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C0
     *
     * @param c0 the value for ONLINEQC.QC_POPUPINFO.C0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC0(Object c0) {
        this.c0 = c0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C1
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C1
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC1() {
        return c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C1
     *
     * @param c1 the value for ONLINEQC.QC_POPUPINFO.C1
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC1(Object c1) {
        this.c1 = c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C2
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C2
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC2() {
        return c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C2
     *
     * @param c2 the value for ONLINEQC.QC_POPUPINFO.C2
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC2(Object c2) {
        this.c2 = c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C3
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C3
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC3() {
        return c3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C3
     *
     * @param c3 the value for ONLINEQC.QC_POPUPINFO.C3
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC3(Object c3) {
        this.c3 = c3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C4
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C4
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC4() {
        return c4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C4
     *
     * @param c4 the value for ONLINEQC.QC_POPUPINFO.C4
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC4(Object c4) {
        this.c4 = c4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C5
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C5
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC5() {
        return c5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C5
     *
     * @param c5 the value for ONLINEQC.QC_POPUPINFO.C5
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC5(Object c5) {
        this.c5 = c5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C6
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C6
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC6() {
        return c6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C6
     *
     * @param c6 the value for ONLINEQC.QC_POPUPINFO.C6
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC6(Object c6) {
        this.c6 = c6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C7
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C7
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC7() {
        return c7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C7
     *
     * @param c7 the value for ONLINEQC.QC_POPUPINFO.C7
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC7(Object c7) {
        this.c7 = c7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C8
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C8
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC8() {
        return c8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C8
     *
     * @param c8 the value for ONLINEQC.QC_POPUPINFO.C8
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC8(Object c8) {
        this.c8 = c8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C9
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C9
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC9() {
        return c9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C9
     *
     * @param c9 the value for ONLINEQC.QC_POPUPINFO.C9
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC9(Object c9) {
        this.c9 = c9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C10
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C10
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC10() {
        return c10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C10
     *
     * @param c10 the value for ONLINEQC.QC_POPUPINFO.C10
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC10(Object c10) {
        this.c10 = c10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C11
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C11
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC11() {
        return c11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C11
     *
     * @param c11 the value for ONLINEQC.QC_POPUPINFO.C11
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC11(Object c11) {
        this.c11 = c11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C12
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C12
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC12() {
        return c12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C12
     *
     * @param c12 the value for ONLINEQC.QC_POPUPINFO.C12
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC12(Object c12) {
        this.c12 = c12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C13
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C13
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC13() {
        return c13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C13
     *
     * @param c13 the value for ONLINEQC.QC_POPUPINFO.C13
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC13(Object c13) {
        this.c13 = c13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C14
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C14
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC14() {
        return c14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C14
     *
     * @param c14 the value for ONLINEQC.QC_POPUPINFO.C14
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC14(Object c14) {
        this.c14 = c14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C15
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C15
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC15() {
        return c15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C15
     *
     * @param c15 the value for ONLINEQC.QC_POPUPINFO.C15
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC15(Object c15) {
        this.c15 = c15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C16
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C16
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC16() {
        return c16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C16
     *
     * @param c16 the value for ONLINEQC.QC_POPUPINFO.C16
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC16(Object c16) {
        this.c16 = c16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C17
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C17
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC17() {
        return c17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C17
     *
     * @param c17 the value for ONLINEQC.QC_POPUPINFO.C17
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC17(Object c17) {
        this.c17 = c17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C18
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C18
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC18() {
        return c18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C18
     *
     * @param c18 the value for ONLINEQC.QC_POPUPINFO.C18
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC18(Object c18) {
        this.c18 = c18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C19
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C19
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC19() {
        return c19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C19
     *
     * @param c19 the value for ONLINEQC.QC_POPUPINFO.C19
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC19(Object c19) {
        this.c19 = c19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C20
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C20
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC20() {
        return c20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C20
     *
     * @param c20 the value for ONLINEQC.QC_POPUPINFO.C20
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC20(Object c20) {
        this.c20 = c20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C21
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C21
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC21() {
        return c21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C21
     *
     * @param c21 the value for ONLINEQC.QC_POPUPINFO.C21
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC21(Object c21) {
        this.c21 = c21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C22
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C22
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC22() {
        return c22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C22
     *
     * @param c22 the value for ONLINEQC.QC_POPUPINFO.C22
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC22(Object c22) {
        this.c22 = c22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C23
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C23
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC23() {
        return c23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C23
     *
     * @param c23 the value for ONLINEQC.QC_POPUPINFO.C23
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC23(Object c23) {
        this.c23 = c23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C24
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C24
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC24() {
        return c24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C24
     *
     * @param c24 the value for ONLINEQC.QC_POPUPINFO.C24
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC24(Object c24) {
        this.c24 = c24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C25
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C25
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC25() {
        return c25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C25
     *
     * @param c25 the value for ONLINEQC.QC_POPUPINFO.C25
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC25(Object c25) {
        this.c25 = c25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C26
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C26
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC26() {
        return c26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C26
     *
     * @param c26 the value for ONLINEQC.QC_POPUPINFO.C26
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC26(Object c26) {
        this.c26 = c26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C27
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C27
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC27() {
        return c27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C27
     *
     * @param c27 the value for ONLINEQC.QC_POPUPINFO.C27
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC27(Object c27) {
        this.c27 = c27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C28
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C28
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC28() {
        return c28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C28
     *
     * @param c28 the value for ONLINEQC.QC_POPUPINFO.C28
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC28(Object c28) {
        this.c28 = c28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_POPUPINFO.C29
     *
     * @return the value of ONLINEQC.QC_POPUPINFO.C29
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Object getC29() {
        return c29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_POPUPINFO.C29
     *
     * @param c29 the value for ONLINEQC.QC_POPUPINFO.C29
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setC29(Object c29) {
        this.c29 = c29;
    }
}