package com.spring.model1;

public class QcTalktexttabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_TALKTEXTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.QC_TALKTEXTTAB.TTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Long ttid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_TALKTEXTTAB.TENANTID
     *
     * @return the value of ONLINEQC.QC_TALKTEXTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_TALKTEXTTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.QC_TALKTEXTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.QC_TALKTEXTTAB.TTID
     *
     * @return the value of ONLINEQC.QC_TALKTEXTTAB.TTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Long getTtid() {
        return ttid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.QC_TALKTEXTTAB.TTID
     *
     * @param ttid the value for ONLINEQC.QC_TALKTEXTTAB.TTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTtid(Long ttid) {
        this.ttid = ttid;
    }
}