package com.spring.model1;

public class YAgagentgroupqueueopttabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OPTIONID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String optionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String destsysid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OBJECTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String objectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String objecttype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OPTIONID
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OPTIONID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getOptionid() {
        return optionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OPTIONID
     *
     * @param optionid the value for ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OPTIONID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setOptionid(String optionid) {
        this.optionid = optionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.DESTSYSID
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getDestsysid() {
        return destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.DESTSYSID
     *
     * @param destsysid the value for ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setDestsysid(String destsysid) {
        this.destsysid = destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OBJECTNAME
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OBJECTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getObjectname() {
        return objectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OBJECTNAME
     *
     * @param objectname the value for ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OBJECTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setObjectname(String objectname) {
        this.objectname = objectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OBJECTTYPE
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getObjecttype() {
        return objecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OBJECTTYPE
     *
     * @param objecttype the value for ONLINEQC.Y_AGAGENTGROUPQUEUEOPTTAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setObjecttype(String objecttype) {
        this.objecttype = objecttype;
    }
}