package com.spring.model1;

import java.util.Date;

public class YAgagentgrouptab extends YAgagentgrouptabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPTAB.AGENTGROUPALIAS
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String agentgroupalias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPTAB.AGENTGROUPTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String agentgrouptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPTAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private Date lastchangetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER1
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String reserver1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER2
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String reserver2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER3
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String reserver3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.AGENTGROUPALIAS
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPTAB.AGENTGROUPALIAS
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getAgentgroupalias() {
        return agentgroupalias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.AGENTGROUPALIAS
     *
     * @param agentgroupalias the value for ONLINEQC.Y_AGAGENTGROUPTAB.AGENTGROUPALIAS
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setAgentgroupalias(String agentgroupalias) {
        this.agentgroupalias = agentgroupalias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.AGENTGROUPTYPE
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPTAB.AGENTGROUPTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getAgentgrouptype() {
        return agentgrouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.AGENTGROUPTYPE
     *
     * @param agentgrouptype the value for ONLINEQC.Y_AGAGENTGROUPTAB.AGENTGROUPTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setAgentgrouptype(String agentgrouptype) {
        this.agentgrouptype = agentgrouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.LASTCHANGETIME
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPTAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public Date getLastchangetime() {
        return lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.LASTCHANGETIME
     *
     * @param lastchangetime the value for ONLINEQC.Y_AGAGENTGROUPTAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setLastchangetime(Date lastchangetime) {
        this.lastchangetime = lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER1
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER1
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getReserver1() {
        return reserver1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER1
     *
     * @param reserver1 the value for ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER1
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setReserver1(String reserver1) {
        this.reserver1 = reserver1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER2
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER2
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getReserver2() {
        return reserver2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER2
     *
     * @param reserver2 the value for ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER2
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setReserver2(String reserver2) {
        this.reserver2 = reserver2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER3
     *
     * @return the value of ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER3
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getReserver3() {
        return reserver3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER3
     *
     * @param reserver3 the value for ONLINEQC.Y_AGAGENTGROUPTAB.RESERVER3
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setReserver3(String reserver3) {
        this.reserver3 = reserver3;
    }
}