package com.spring.model1;

public class YAgdntabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGDNTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGDNTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String destsysid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGDNTAB.DNNUMBER
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String dnnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_AGDNTAB.SWITCHNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String switchname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGDNTAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_AGDNTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGDNTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_AGDNTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGDNTAB.DESTSYSID
     *
     * @return the value of ONLINEQC.Y_AGDNTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getDestsysid() {
        return destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGDNTAB.DESTSYSID
     *
     * @param destsysid the value for ONLINEQC.Y_AGDNTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setDestsysid(String destsysid) {
        this.destsysid = destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGDNTAB.DNNUMBER
     *
     * @return the value of ONLINEQC.Y_AGDNTAB.DNNUMBER
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getDnnumber() {
        return dnnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGDNTAB.DNNUMBER
     *
     * @param dnnumber the value for ONLINEQC.Y_AGDNTAB.DNNUMBER
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setDnnumber(String dnnumber) {
        this.dnnumber = dnnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_AGDNTAB.SWITCHNAME
     *
     * @return the value of ONLINEQC.Y_AGDNTAB.SWITCHNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getSwitchname() {
        return switchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_AGDNTAB.SWITCHNAME
     *
     * @param switchname the value for ONLINEQC.Y_AGDNTAB.SWITCHNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setSwitchname(String switchname) {
        this.switchname = switchname;
    }
}