package com.spring.model1;

import java.util.Date;

public class YCfacetgroupobjecttab extends YCfacetgroupobjecttabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String destsysid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String objecttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.OBJECTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String objectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATORID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private Long creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATORNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String creatorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private Date changetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGERID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private Long changerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGERNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String changername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.DESTSYSID
     *
     * @return the value of ONLINEQC.Y_CFACETGROUPOBJECTTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getDestsysid() {
        return destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.DESTSYSID
     *
     * @param destsysid the value for ONLINEQC.Y_CFACETGROUPOBJECTTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setDestsysid(String destsysid) {
        this.destsysid = destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.OBJECTTYPE
     *
     * @return the value of ONLINEQC.Y_CFACETGROUPOBJECTTAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getObjecttype() {
        return objecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.OBJECTTYPE
     *
     * @param objecttype the value for ONLINEQC.Y_CFACETGROUPOBJECTTAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setObjecttype(String objecttype) {
        this.objecttype = objecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.OBJECTNAME
     *
     * @return the value of ONLINEQC.Y_CFACETGROUPOBJECTTAB.OBJECTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getObjectname() {
        return objectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.OBJECTNAME
     *
     * @param objectname the value for ONLINEQC.Y_CFACETGROUPOBJECTTAB.OBJECTNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setObjectname(String objectname) {
        this.objectname = objectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATETIME
     *
     * @return the value of ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATETIME
     *
     * @param createtime the value for ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATORID
     *
     * @return the value of ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATORID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public Long getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATORID
     *
     * @param creatorid the value for ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATORID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setCreatorid(Long creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATORNAME
     *
     * @return the value of ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATORNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getCreatorname() {
        return creatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATORNAME
     *
     * @param creatorname the value for ONLINEQC.Y_CFACETGROUPOBJECTTAB.CREATORNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setCreatorname(String creatorname) {
        this.creatorname = creatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGETIME
     *
     * @return the value of ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public Date getChangetime() {
        return changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGETIME
     *
     * @param changetime the value for ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setChangetime(Date changetime) {
        this.changetime = changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGERID
     *
     * @return the value of ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGERID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public Long getChangerid() {
        return changerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGERID
     *
     * @param changerid the value for ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGERID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setChangerid(Long changerid) {
        this.changerid = changerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGERNAME
     *
     * @return the value of ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGERNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getChangername() {
        return changername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGERNAME
     *
     * @param changername the value for ONLINEQC.Y_CFACETGROUPOBJECTTAB.CHANGERNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setChangername(String changername) {
        this.changername = changername;
    }
}