package com.spring.model1;

import java.util.Date;

public class YChfacetobjecttabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CHFACETOBJECTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CHFACETOBJECTTAB.VER
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private Date ver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CHFACETOBJECTTAB.OBJECTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String objectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_CHFACETOBJECTTAB.FACETVALUEID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private Long facetvalueid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CHFACETOBJECTTAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_CHFACETOBJECTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CHFACETOBJECTTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_CHFACETOBJECTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CHFACETOBJECTTAB.VER
     *
     * @return the value of ONLINEQC.Y_CHFACETOBJECTTAB.VER
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public Date getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CHFACETOBJECTTAB.VER
     *
     * @param ver the value for ONLINEQC.Y_CHFACETOBJECTTAB.VER
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setVer(Date ver) {
        this.ver = ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CHFACETOBJECTTAB.OBJECTID
     *
     * @return the value of ONLINEQC.Y_CHFACETOBJECTTAB.OBJECTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getObjectid() {
        return objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CHFACETOBJECTTAB.OBJECTID
     *
     * @param objectid the value for ONLINEQC.Y_CHFACETOBJECTTAB.OBJECTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setObjectid(String objectid) {
        this.objectid = objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_CHFACETOBJECTTAB.FACETVALUEID
     *
     * @return the value of ONLINEQC.Y_CHFACETOBJECTTAB.FACETVALUEID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public Long getFacetvalueid() {
        return facetvalueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_CHFACETOBJECTTAB.FACETVALUEID
     *
     * @param facetvalueid the value for ONLINEQC.Y_CHFACETOBJECTTAB.FACETVALUEID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setFacetvalueid(Long facetvalueid) {
        this.facetvalueid = facetvalueid;
    }
}