package com.spring.model1;

import java.math.BigDecimal;

public class YCobjectthresholdconfigtab extends YCobjectthresholdconfigtabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_COBJECTTHRESHOLDCONFIGTAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String objecttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_COBJECTTHRESHOLDCONFIGTAB.CONFIGINDEX
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private BigDecimal configindex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_COBJECTTHRESHOLDCONFIGTAB.OBJECTTYPE
     *
     * @return the value of ONLINEQC.Y_COBJECTTHRESHOLDCONFIGTAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getObjecttype() {
        return objecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_COBJECTTHRESHOLDCONFIGTAB.OBJECTTYPE
     *
     * @param objecttype the value for ONLINEQC.Y_COBJECTTHRESHOLDCONFIGTAB.OBJECTTYPE
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setObjecttype(String objecttype) {
        this.objecttype = objecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_COBJECTTHRESHOLDCONFIGTAB.CONFIGINDEX
     *
     * @return the value of ONLINEQC.Y_COBJECTTHRESHOLDCONFIGTAB.CONFIGINDEX
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public BigDecimal getConfigindex() {
        return configindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_COBJECTTHRESHOLDCONFIGTAB.CONFIGINDEX
     *
     * @param configindex the value for ONLINEQC.Y_COBJECTTHRESHOLDCONFIGTAB.CONFIGINDEX
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setConfigindex(BigDecimal configindex) {
        this.configindex = configindex;
    }
}