package com.spring.model1;

public class YCobjectinfotabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_COBJECTINFOTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_COBJECTINFOTAB.OBJECTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String objectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_COBJECTINFOTAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_COBJECTINFOTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_COBJECTINFOTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_COBJECTINFOTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_COBJECTINFOTAB.OBJECTID
     *
     * @return the value of ONLINEQC.Y_COBJECTINFOTAB.OBJECTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getObjectid() {
        return objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_COBJECTINFOTAB.OBJECTID
     *
     * @param objectid the value for ONLINEQC.Y_COBJECTINFOTAB.OBJECTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setObjectid(String objectid) {
        this.objectid = objectid;
    }
}