package com.spring.model1;

public class YDestsysmappingbuslinetabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB.BUSLINE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String busline;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB.BUSLINE
     *
     * @return the value of ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB.BUSLINE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getBusline() {
        return busline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB.BUSLINE
     *
     * @param busline the value for ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB.BUSLINE
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setBusline(String busline) {
        this.busline = busline;
    }
}