package com.spring.model1;

import java.math.BigDecimal;
import java.util.Date;

public class YDgagentstatusinfotab extends YDgagentstatusinfotabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.EVENTSEQ
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String eventseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DN
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DNSTATUS
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String dnstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.ACTIONTIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private BigDecimal actiontime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.PERSONNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String personname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private Date lastchangetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.NOTREADYREASON
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String notreadyreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE1
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE2
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE3
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String reserve3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.EVENTSEQ
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.EVENTSEQ
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getEventseq() {
        return eventseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.EVENTSEQ
     *
     * @param eventseq the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.EVENTSEQ
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setEventseq(String eventseq) {
        this.eventseq = eventseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DN
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DN
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getDn() {
        return dn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DN
     *
     * @param dn the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DN
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setDn(String dn) {
        this.dn = dn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DNSTATUS
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DNSTATUS
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getDnstatus() {
        return dnstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DNSTATUS
     *
     * @param dnstatus the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DNSTATUS
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setDnstatus(String dnstatus) {
        this.dnstatus = dnstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.ACTIONTIME
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.ACTIONTIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public BigDecimal getActiontime() {
        return actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.ACTIONTIME
     *
     * @param actiontime the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.ACTIONTIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setActiontime(BigDecimal actiontime) {
        this.actiontime = actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.PERSONNAME
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.PERSONNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getPersonname() {
        return personname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.PERSONNAME
     *
     * @param personname the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.PERSONNAME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setPersonname(String personname) {
        this.personname = personname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.LASTCHANGETIME
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public Date getLastchangetime() {
        return lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.LASTCHANGETIME
     *
     * @param lastchangetime the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setLastchangetime(Date lastchangetime) {
        this.lastchangetime = lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.NOTREADYREASON
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.NOTREADYREASON
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getNotreadyreason() {
        return notreadyreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.NOTREADYREASON
     *
     * @param notreadyreason the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.NOTREADYREASON
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setNotreadyreason(String notreadyreason) {
        this.notreadyreason = notreadyreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE1
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE1
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE1
     *
     * @param reserve1 the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE1
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE2
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE2
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE2
     *
     * @param reserve2 the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE2
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE3
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE3
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE3
     *
     * @param reserve3 the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.RESERVE3
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3;
    }
}