package com.spring.model1;

public class YDgagentstatusinfotabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String destsysid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.AGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String agentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.SEQID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    private String seqid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DESTSYSID
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getDestsysid() {
        return destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DESTSYSID
     *
     * @param destsysid the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setDestsysid(String destsysid) {
        this.destsysid = destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.AGENTID
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.AGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.AGENTID
     *
     * @param agentid the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.AGENTID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.SEQID
     *
     * @return the value of ONLINEQC.Y_DGAGENTSTATUSINFOTAB.SEQID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public String getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_DGAGENTSTATUSINFOTAB.SEQID
     *
     * @param seqid the value for ONLINEQC.Y_DGAGENTSTATUSINFOTAB.SEQID
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    public void setSeqid(String seqid) {
        this.seqid = seqid;
    }
}