package com.spring.model1;

import java.util.Date;

public class YMdirectorstatuschangeinfotab extends YMdirectorstatuschangeinfotabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.USERUM
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String userum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.STATUS
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.STATUSCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Date statuschangetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.USERUM
     *
     * @return the value of ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.USERUM
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getUserum() {
        return userum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.USERUM
     *
     * @param userum the value for ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.USERUM
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setUserum(String userum) {
        this.userum = userum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.STATUS
     *
     * @return the value of ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.STATUS
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.STATUS
     *
     * @param status the value for ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.STATUS
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.STATUSCHANGETIME
     *
     * @return the value of ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.STATUSCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Date getStatuschangetime() {
        return statuschangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.STATUSCHANGETIME
     *
     * @param statuschangetime the value for ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB.STATUSCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setStatuschangetime(Date statuschangetime) {
        this.statuschangetime = statuschangetime;
    }
}