package com.spring.model1;

public class YMindexrelatedtabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_MINDEXRELATEDTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_MINDEXRELATEDTAB.INDEXID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String indexid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_MINDEXRELATEDTAB.RELATEDINDEXID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String relatedindexid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_MINDEXRELATEDTAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_MINDEXRELATEDTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_MINDEXRELATEDTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_MINDEXRELATEDTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_MINDEXRELATEDTAB.INDEXID
     *
     * @return the value of ONLINEQC.Y_MINDEXRELATEDTAB.INDEXID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getIndexid() {
        return indexid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_MINDEXRELATEDTAB.INDEXID
     *
     * @param indexid the value for ONLINEQC.Y_MINDEXRELATEDTAB.INDEXID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setIndexid(String indexid) {
        this.indexid = indexid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_MINDEXRELATEDTAB.RELATEDINDEXID
     *
     * @return the value of ONLINEQC.Y_MINDEXRELATEDTAB.RELATEDINDEXID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getRelatedindexid() {
        return relatedindexid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_MINDEXRELATEDTAB.RELATEDINDEXID
     *
     * @param relatedindexid the value for ONLINEQC.Y_MINDEXRELATEDTAB.RELATEDINDEXID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setRelatedindexid(String relatedindexid) {
        this.relatedindexid = relatedindexid;
    }
}