package com.spring.model1;

public class YMseatpointtabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_MSEATPOINTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_MSEATPOINTTAB.NODEID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private Long nodeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_MSEATPOINTTAB.SEATID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    private String seatid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_MSEATPOINTTAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_MSEATPOINTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_MSEATPOINTTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_MSEATPOINTTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_MSEATPOINTTAB.NODEID
     *
     * @return the value of ONLINEQC.Y_MSEATPOINTTAB.NODEID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public Long getNodeid() {
        return nodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_MSEATPOINTTAB.NODEID
     *
     * @param nodeid the value for ONLINEQC.Y_MSEATPOINTTAB.NODEID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setNodeid(Long nodeid) {
        this.nodeid = nodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_MSEATPOINTTAB.SEATID
     *
     * @return the value of ONLINEQC.Y_MSEATPOINTTAB.SEATID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public String getSeatid() {
        return seatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_MSEATPOINTTAB.SEATID
     *
     * @param seatid the value for ONLINEQC.Y_MSEATPOINTTAB.SEATID
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    public void setSeatid(String seatid) {
        this.seatid = seatid;
    }
}