package com.spring.model1;

public class YRgagentgroup2persontabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String destsysid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.AGENTGROUPDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String agentgroupdbid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.PERSONDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String persondbid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.DESTSYSID
     *
     * @return the value of ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getDestsysid() {
        return destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.DESTSYSID
     *
     * @param destsysid the value for ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setDestsysid(String destsysid) {
        this.destsysid = destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.AGENTGROUPDBID
     *
     * @return the value of ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.AGENTGROUPDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getAgentgroupdbid() {
        return agentgroupdbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.AGENTGROUPDBID
     *
     * @param agentgroupdbid the value for ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.AGENTGROUPDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setAgentgroupdbid(String agentgroupdbid) {
        this.agentgroupdbid = agentgroupdbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.PERSONDBID
     *
     * @return the value of ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.PERSONDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getPersondbid() {
        return persondbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.PERSONDBID
     *
     * @param persondbid the value for ONLINEQC.Y_RGAGENTGROUP2PERSONTAB.PERSONDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setPersondbid(String persondbid) {
        this.persondbid = persondbid;
    }
}