package com.spring.model1;

import java.util.Date;

public class YRgplacetab extends YRgplacetabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGPLACETAB.PLACENAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String placename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGPLACETAB.PLACECONFPATH
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String placeconfpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGPLACETAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private Date lastchangetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGPLACETAB.RESERVER1
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String reserver1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGPLACETAB.RESERVER2
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String reserver2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGPLACETAB.RESERVER3
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String reserver3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGPLACETAB.PLACENAME
     *
     * @return the value of ONLINEQC.Y_RGPLACETAB.PLACENAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getPlacename() {
        return placename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGPLACETAB.PLACENAME
     *
     * @param placename the value for ONLINEQC.Y_RGPLACETAB.PLACENAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setPlacename(String placename) {
        this.placename = placename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGPLACETAB.PLACECONFPATH
     *
     * @return the value of ONLINEQC.Y_RGPLACETAB.PLACECONFPATH
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getPlaceconfpath() {
        return placeconfpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGPLACETAB.PLACECONFPATH
     *
     * @param placeconfpath the value for ONLINEQC.Y_RGPLACETAB.PLACECONFPATH
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setPlaceconfpath(String placeconfpath) {
        this.placeconfpath = placeconfpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGPLACETAB.LASTCHANGETIME
     *
     * @return the value of ONLINEQC.Y_RGPLACETAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public Date getLastchangetime() {
        return lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGPLACETAB.LASTCHANGETIME
     *
     * @param lastchangetime the value for ONLINEQC.Y_RGPLACETAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setLastchangetime(Date lastchangetime) {
        this.lastchangetime = lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGPLACETAB.RESERVER1
     *
     * @return the value of ONLINEQC.Y_RGPLACETAB.RESERVER1
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getReserver1() {
        return reserver1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGPLACETAB.RESERVER1
     *
     * @param reserver1 the value for ONLINEQC.Y_RGPLACETAB.RESERVER1
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setReserver1(String reserver1) {
        this.reserver1 = reserver1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGPLACETAB.RESERVER2
     *
     * @return the value of ONLINEQC.Y_RGPLACETAB.RESERVER2
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getReserver2() {
        return reserver2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGPLACETAB.RESERVER2
     *
     * @param reserver2 the value for ONLINEQC.Y_RGPLACETAB.RESERVER2
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setReserver2(String reserver2) {
        this.reserver2 = reserver2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGPLACETAB.RESERVER3
     *
     * @return the value of ONLINEQC.Y_RGPLACETAB.RESERVER3
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getReserver3() {
        return reserver3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGPLACETAB.RESERVER3
     *
     * @param reserver3 the value for ONLINEQC.Y_RGPLACETAB.RESERVER3
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setReserver3(String reserver3) {
        this.reserver3 = reserver3;
    }
}