package com.spring.model1;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class YRgpersontabExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public YRgpersontabExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTenantidIsNull() {
            addCriterion("TENANTID is null");
            return (Criteria) this;
        }

        public Criteria andTenantidIsNotNull() {
            addCriterion("TENANTID is not null");
            return (Criteria) this;
        }

        public Criteria andTenantidEqualTo(String value) {
            addCriterion("TENANTID =", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotEqualTo(String value) {
            addCriterion("TENANTID <>", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidGreaterThan(String value) {
            addCriterion("TENANTID >", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidGreaterThanOrEqualTo(String value) {
            addCriterion("TENANTID >=", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidLessThan(String value) {
            addCriterion("TENANTID <", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidLessThanOrEqualTo(String value) {
            addCriterion("TENANTID <=", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidLike(String value) {
            addCriterion("TENANTID like", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotLike(String value) {
            addCriterion("TENANTID not like", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidIn(List<String> values) {
            addCriterion("TENANTID in", values, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotIn(List<String> values) {
            addCriterion("TENANTID not in", values, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidBetween(String value1, String value2) {
            addCriterion("TENANTID between", value1, value2, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotBetween(String value1, String value2) {
            addCriterion("TENANTID not between", value1, value2, "tenantid");
            return (Criteria) this;
        }

        public Criteria andDestsysidIsNull() {
            addCriterion("DESTSYSID is null");
            return (Criteria) this;
        }

        public Criteria andDestsysidIsNotNull() {
            addCriterion("DESTSYSID is not null");
            return (Criteria) this;
        }

        public Criteria andDestsysidEqualTo(String value) {
            addCriterion("DESTSYSID =", value, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidNotEqualTo(String value) {
            addCriterion("DESTSYSID <>", value, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidGreaterThan(String value) {
            addCriterion("DESTSYSID >", value, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidGreaterThanOrEqualTo(String value) {
            addCriterion("DESTSYSID >=", value, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidLessThan(String value) {
            addCriterion("DESTSYSID <", value, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidLessThanOrEqualTo(String value) {
            addCriterion("DESTSYSID <=", value, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidLike(String value) {
            addCriterion("DESTSYSID like", value, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidNotLike(String value) {
            addCriterion("DESTSYSID not like", value, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidIn(List<String> values) {
            addCriterion("DESTSYSID in", values, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidNotIn(List<String> values) {
            addCriterion("DESTSYSID not in", values, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidBetween(String value1, String value2) {
            addCriterion("DESTSYSID between", value1, value2, "destsysid");
            return (Criteria) this;
        }

        public Criteria andDestsysidNotBetween(String value1, String value2) {
            addCriterion("DESTSYSID not between", value1, value2, "destsysid");
            return (Criteria) this;
        }

        public Criteria andPersondbidIsNull() {
            addCriterion("PERSONDBID is null");
            return (Criteria) this;
        }

        public Criteria andPersondbidIsNotNull() {
            addCriterion("PERSONDBID is not null");
            return (Criteria) this;
        }

        public Criteria andPersondbidEqualTo(String value) {
            addCriterion("PERSONDBID =", value, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidNotEqualTo(String value) {
            addCriterion("PERSONDBID <>", value, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidGreaterThan(String value) {
            addCriterion("PERSONDBID >", value, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidGreaterThanOrEqualTo(String value) {
            addCriterion("PERSONDBID >=", value, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidLessThan(String value) {
            addCriterion("PERSONDBID <", value, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidLessThanOrEqualTo(String value) {
            addCriterion("PERSONDBID <=", value, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidLike(String value) {
            addCriterion("PERSONDBID like", value, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidNotLike(String value) {
            addCriterion("PERSONDBID not like", value, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidIn(List<String> values) {
            addCriterion("PERSONDBID in", values, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidNotIn(List<String> values) {
            addCriterion("PERSONDBID not in", values, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidBetween(String value1, String value2) {
            addCriterion("PERSONDBID between", value1, value2, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersondbidNotBetween(String value1, String value2) {
            addCriterion("PERSONDBID not between", value1, value2, "persondbid");
            return (Criteria) this;
        }

        public Criteria andPersonusernameIsNull() {
            addCriterion("PERSONUSERNAME is null");
            return (Criteria) this;
        }

        public Criteria andPersonusernameIsNotNull() {
            addCriterion("PERSONUSERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPersonusernameEqualTo(String value) {
            addCriterion("PERSONUSERNAME =", value, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameNotEqualTo(String value) {
            addCriterion("PERSONUSERNAME <>", value, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameGreaterThan(String value) {
            addCriterion("PERSONUSERNAME >", value, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameGreaterThanOrEqualTo(String value) {
            addCriterion("PERSONUSERNAME >=", value, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameLessThan(String value) {
            addCriterion("PERSONUSERNAME <", value, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameLessThanOrEqualTo(String value) {
            addCriterion("PERSONUSERNAME <=", value, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameLike(String value) {
            addCriterion("PERSONUSERNAME like", value, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameNotLike(String value) {
            addCriterion("PERSONUSERNAME not like", value, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameIn(List<String> values) {
            addCriterion("PERSONUSERNAME in", values, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameNotIn(List<String> values) {
            addCriterion("PERSONUSERNAME not in", values, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameBetween(String value1, String value2) {
            addCriterion("PERSONUSERNAME between", value1, value2, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonusernameNotBetween(String value1, String value2) {
            addCriterion("PERSONUSERNAME not between", value1, value2, "personusername");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameIsNull() {
            addCriterion("PERSONFIRSTNAME is null");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameIsNotNull() {
            addCriterion("PERSONFIRSTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameEqualTo(String value) {
            addCriterion("PERSONFIRSTNAME =", value, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameNotEqualTo(String value) {
            addCriterion("PERSONFIRSTNAME <>", value, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameGreaterThan(String value) {
            addCriterion("PERSONFIRSTNAME >", value, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameGreaterThanOrEqualTo(String value) {
            addCriterion("PERSONFIRSTNAME >=", value, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameLessThan(String value) {
            addCriterion("PERSONFIRSTNAME <", value, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameLessThanOrEqualTo(String value) {
            addCriterion("PERSONFIRSTNAME <=", value, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameLike(String value) {
            addCriterion("PERSONFIRSTNAME like", value, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameNotLike(String value) {
            addCriterion("PERSONFIRSTNAME not like", value, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameIn(List<String> values) {
            addCriterion("PERSONFIRSTNAME in", values, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameNotIn(List<String> values) {
            addCriterion("PERSONFIRSTNAME not in", values, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameBetween(String value1, String value2) {
            addCriterion("PERSONFIRSTNAME between", value1, value2, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonfirstnameNotBetween(String value1, String value2) {
            addCriterion("PERSONFIRSTNAME not between", value1, value2, "personfirstname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameIsNull() {
            addCriterion("PERSONLASTNAME is null");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameIsNotNull() {
            addCriterion("PERSONLASTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameEqualTo(String value) {
            addCriterion("PERSONLASTNAME =", value, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameNotEqualTo(String value) {
            addCriterion("PERSONLASTNAME <>", value, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameGreaterThan(String value) {
            addCriterion("PERSONLASTNAME >", value, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameGreaterThanOrEqualTo(String value) {
            addCriterion("PERSONLASTNAME >=", value, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameLessThan(String value) {
            addCriterion("PERSONLASTNAME <", value, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameLessThanOrEqualTo(String value) {
            addCriterion("PERSONLASTNAME <=", value, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameLike(String value) {
            addCriterion("PERSONLASTNAME like", value, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameNotLike(String value) {
            addCriterion("PERSONLASTNAME not like", value, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameIn(List<String> values) {
            addCriterion("PERSONLASTNAME in", values, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameNotIn(List<String> values) {
            addCriterion("PERSONLASTNAME not in", values, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameBetween(String value1, String value2) {
            addCriterion("PERSONLASTNAME between", value1, value2, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonlastnameNotBetween(String value1, String value2) {
            addCriterion("PERSONLASTNAME not between", value1, value2, "personlastname");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidIsNull() {
            addCriterion("PERSONEMPLOYEEID is null");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidIsNotNull() {
            addCriterion("PERSONEMPLOYEEID is not null");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidEqualTo(String value) {
            addCriterion("PERSONEMPLOYEEID =", value, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidNotEqualTo(String value) {
            addCriterion("PERSONEMPLOYEEID <>", value, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidGreaterThan(String value) {
            addCriterion("PERSONEMPLOYEEID >", value, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidGreaterThanOrEqualTo(String value) {
            addCriterion("PERSONEMPLOYEEID >=", value, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidLessThan(String value) {
            addCriterion("PERSONEMPLOYEEID <", value, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidLessThanOrEqualTo(String value) {
            addCriterion("PERSONEMPLOYEEID <=", value, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidLike(String value) {
            addCriterion("PERSONEMPLOYEEID like", value, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidNotLike(String value) {
            addCriterion("PERSONEMPLOYEEID not like", value, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidIn(List<String> values) {
            addCriterion("PERSONEMPLOYEEID in", values, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidNotIn(List<String> values) {
            addCriterion("PERSONEMPLOYEEID not in", values, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidBetween(String value1, String value2) {
            addCriterion("PERSONEMPLOYEEID between", value1, value2, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemployeeidNotBetween(String value1, String value2) {
            addCriterion("PERSONEMPLOYEEID not between", value1, value2, "personemployeeid");
            return (Criteria) this;
        }

        public Criteria andPersonemailIsNull() {
            addCriterion("PERSONEMAIL is null");
            return (Criteria) this;
        }

        public Criteria andPersonemailIsNotNull() {
            addCriterion("PERSONEMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andPersonemailEqualTo(String value) {
            addCriterion("PERSONEMAIL =", value, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailNotEqualTo(String value) {
            addCriterion("PERSONEMAIL <>", value, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailGreaterThan(String value) {
            addCriterion("PERSONEMAIL >", value, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailGreaterThanOrEqualTo(String value) {
            addCriterion("PERSONEMAIL >=", value, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailLessThan(String value) {
            addCriterion("PERSONEMAIL <", value, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailLessThanOrEqualTo(String value) {
            addCriterion("PERSONEMAIL <=", value, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailLike(String value) {
            addCriterion("PERSONEMAIL like", value, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailNotLike(String value) {
            addCriterion("PERSONEMAIL not like", value, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailIn(List<String> values) {
            addCriterion("PERSONEMAIL in", values, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailNotIn(List<String> values) {
            addCriterion("PERSONEMAIL not in", values, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailBetween(String value1, String value2) {
            addCriterion("PERSONEMAIL between", value1, value2, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersonemailNotBetween(String value1, String value2) {
            addCriterion("PERSONEMAIL not between", value1, value2, "personemail");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathIsNull() {
            addCriterion("PERSONCONTPATH is null");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathIsNotNull() {
            addCriterion("PERSONCONTPATH is not null");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathEqualTo(String value) {
            addCriterion("PERSONCONTPATH =", value, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathNotEqualTo(String value) {
            addCriterion("PERSONCONTPATH <>", value, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathGreaterThan(String value) {
            addCriterion("PERSONCONTPATH >", value, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathGreaterThanOrEqualTo(String value) {
            addCriterion("PERSONCONTPATH >=", value, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathLessThan(String value) {
            addCriterion("PERSONCONTPATH <", value, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathLessThanOrEqualTo(String value) {
            addCriterion("PERSONCONTPATH <=", value, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathLike(String value) {
            addCriterion("PERSONCONTPATH like", value, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathNotLike(String value) {
            addCriterion("PERSONCONTPATH not like", value, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathIn(List<String> values) {
            addCriterion("PERSONCONTPATH in", values, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathNotIn(List<String> values) {
            addCriterion("PERSONCONTPATH not in", values, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathBetween(String value1, String value2) {
            addCriterion("PERSONCONTPATH between", value1, value2, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andPersoncontpathNotBetween(String value1, String value2) {
            addCriterion("PERSONCONTPATH not between", value1, value2, "personcontpath");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeIsNull() {
            addCriterion("LASTCHANGETIME is null");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeIsNotNull() {
            addCriterion("LASTCHANGETIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeEqualTo(Date value) {
            addCriterion("LASTCHANGETIME =", value, "lastchangetime");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeNotEqualTo(Date value) {
            addCriterion("LASTCHANGETIME <>", value, "lastchangetime");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeGreaterThan(Date value) {
            addCriterion("LASTCHANGETIME >", value, "lastchangetime");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LASTCHANGETIME >=", value, "lastchangetime");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeLessThan(Date value) {
            addCriterion("LASTCHANGETIME <", value, "lastchangetime");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeLessThanOrEqualTo(Date value) {
            addCriterion("LASTCHANGETIME <=", value, "lastchangetime");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeIn(List<Date> values) {
            addCriterion("LASTCHANGETIME in", values, "lastchangetime");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeNotIn(List<Date> values) {
            addCriterion("LASTCHANGETIME not in", values, "lastchangetime");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeBetween(Date value1, Date value2) {
            addCriterion("LASTCHANGETIME between", value1, value2, "lastchangetime");
            return (Criteria) this;
        }

        public Criteria andLastchangetimeNotBetween(Date value1, Date value2) {
            addCriterion("LASTCHANGETIME not between", value1, value2, "lastchangetime");
            return (Criteria) this;
        }

        public Criteria andReserver1IsNull() {
            addCriterion("RESERVER1 is null");
            return (Criteria) this;
        }

        public Criteria andReserver1IsNotNull() {
            addCriterion("RESERVER1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserver1EqualTo(String value) {
            addCriterion("RESERVER1 =", value, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1NotEqualTo(String value) {
            addCriterion("RESERVER1 <>", value, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1GreaterThan(String value) {
            addCriterion("RESERVER1 >", value, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVER1 >=", value, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1LessThan(String value) {
            addCriterion("RESERVER1 <", value, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1LessThanOrEqualTo(String value) {
            addCriterion("RESERVER1 <=", value, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1Like(String value) {
            addCriterion("RESERVER1 like", value, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1NotLike(String value) {
            addCriterion("RESERVER1 not like", value, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1In(List<String> values) {
            addCriterion("RESERVER1 in", values, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1NotIn(List<String> values) {
            addCriterion("RESERVER1 not in", values, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1Between(String value1, String value2) {
            addCriterion("RESERVER1 between", value1, value2, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver1NotBetween(String value1, String value2) {
            addCriterion("RESERVER1 not between", value1, value2, "reserver1");
            return (Criteria) this;
        }

        public Criteria andReserver2IsNull() {
            addCriterion("RESERVER2 is null");
            return (Criteria) this;
        }

        public Criteria andReserver2IsNotNull() {
            addCriterion("RESERVER2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserver2EqualTo(String value) {
            addCriterion("RESERVER2 =", value, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2NotEqualTo(String value) {
            addCriterion("RESERVER2 <>", value, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2GreaterThan(String value) {
            addCriterion("RESERVER2 >", value, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVER2 >=", value, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2LessThan(String value) {
            addCriterion("RESERVER2 <", value, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2LessThanOrEqualTo(String value) {
            addCriterion("RESERVER2 <=", value, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2Like(String value) {
            addCriterion("RESERVER2 like", value, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2NotLike(String value) {
            addCriterion("RESERVER2 not like", value, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2In(List<String> values) {
            addCriterion("RESERVER2 in", values, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2NotIn(List<String> values) {
            addCriterion("RESERVER2 not in", values, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2Between(String value1, String value2) {
            addCriterion("RESERVER2 between", value1, value2, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver2NotBetween(String value1, String value2) {
            addCriterion("RESERVER2 not between", value1, value2, "reserver2");
            return (Criteria) this;
        }

        public Criteria andReserver3IsNull() {
            addCriterion("RESERVER3 is null");
            return (Criteria) this;
        }

        public Criteria andReserver3IsNotNull() {
            addCriterion("RESERVER3 is not null");
            return (Criteria) this;
        }

        public Criteria andReserver3EqualTo(String value) {
            addCriterion("RESERVER3 =", value, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3NotEqualTo(String value) {
            addCriterion("RESERVER3 <>", value, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3GreaterThan(String value) {
            addCriterion("RESERVER3 >", value, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVER3 >=", value, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3LessThan(String value) {
            addCriterion("RESERVER3 <", value, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3LessThanOrEqualTo(String value) {
            addCriterion("RESERVER3 <=", value, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3Like(String value) {
            addCriterion("RESERVER3 like", value, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3NotLike(String value) {
            addCriterion("RESERVER3 not like", value, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3In(List<String> values) {
            addCriterion("RESERVER3 in", values, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3NotIn(List<String> values) {
            addCriterion("RESERVER3 not in", values, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3Between(String value1, String value2) {
            addCriterion("RESERVER3 between", value1, value2, "reserver3");
            return (Criteria) this;
        }

        public Criteria andReserver3NotBetween(String value1, String value2) {
            addCriterion("RESERVER3 not between", value1, value2, "reserver3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 08 16:40:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ONLINEQC.Y_RGPERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}