package com.spring.model1;

import java.util.Date;

public class YRgqueuetab extends YRgqueuetabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.QUEUESWITCHDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String queueswitchdbid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.QUEUEDNNUM
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String queuednnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.QUEUENAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String queuename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.QUEUEALIAS
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String queuealias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.QUEUETYPE
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String queuetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.QUEUEBUSIPATH
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String queuebusipath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.QUEUECONTPATH
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String queuecontpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private Date lastchangetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.RESERVER1
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String reserver1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.RESERVER2
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String reserver2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGQUEUETAB.RESERVER3
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String reserver3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUESWITCHDBID
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.QUEUESWITCHDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getQueueswitchdbid() {
        return queueswitchdbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUESWITCHDBID
     *
     * @param queueswitchdbid the value for ONLINEQC.Y_RGQUEUETAB.QUEUESWITCHDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setQueueswitchdbid(String queueswitchdbid) {
        this.queueswitchdbid = queueswitchdbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUEDNNUM
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.QUEUEDNNUM
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getQueuednnum() {
        return queuednnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUEDNNUM
     *
     * @param queuednnum the value for ONLINEQC.Y_RGQUEUETAB.QUEUEDNNUM
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setQueuednnum(String queuednnum) {
        this.queuednnum = queuednnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUENAME
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.QUEUENAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getQueuename() {
        return queuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUENAME
     *
     * @param queuename the value for ONLINEQC.Y_RGQUEUETAB.QUEUENAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setQueuename(String queuename) {
        this.queuename = queuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUEALIAS
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.QUEUEALIAS
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getQueuealias() {
        return queuealias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUEALIAS
     *
     * @param queuealias the value for ONLINEQC.Y_RGQUEUETAB.QUEUEALIAS
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setQueuealias(String queuealias) {
        this.queuealias = queuealias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUETYPE
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.QUEUETYPE
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getQueuetype() {
        return queuetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUETYPE
     *
     * @param queuetype the value for ONLINEQC.Y_RGQUEUETAB.QUEUETYPE
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setQueuetype(String queuetype) {
        this.queuetype = queuetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUEBUSIPATH
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.QUEUEBUSIPATH
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getQueuebusipath() {
        return queuebusipath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUEBUSIPATH
     *
     * @param queuebusipath the value for ONLINEQC.Y_RGQUEUETAB.QUEUEBUSIPATH
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setQueuebusipath(String queuebusipath) {
        this.queuebusipath = queuebusipath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUECONTPATH
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.QUEUECONTPATH
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getQueuecontpath() {
        return queuecontpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.QUEUECONTPATH
     *
     * @param queuecontpath the value for ONLINEQC.Y_RGQUEUETAB.QUEUECONTPATH
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setQueuecontpath(String queuecontpath) {
        this.queuecontpath = queuecontpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.LASTCHANGETIME
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public Date getLastchangetime() {
        return lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.LASTCHANGETIME
     *
     * @param lastchangetime the value for ONLINEQC.Y_RGQUEUETAB.LASTCHANGETIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setLastchangetime(Date lastchangetime) {
        this.lastchangetime = lastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.RESERVER1
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.RESERVER1
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getReserver1() {
        return reserver1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.RESERVER1
     *
     * @param reserver1 the value for ONLINEQC.Y_RGQUEUETAB.RESERVER1
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setReserver1(String reserver1) {
        this.reserver1 = reserver1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.RESERVER2
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.RESERVER2
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getReserver2() {
        return reserver2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.RESERVER2
     *
     * @param reserver2 the value for ONLINEQC.Y_RGQUEUETAB.RESERVER2
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setReserver2(String reserver2) {
        this.reserver2 = reserver2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGQUEUETAB.RESERVER3
     *
     * @return the value of ONLINEQC.Y_RGQUEUETAB.RESERVER3
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getReserver3() {
        return reserver3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGQUEUETAB.RESERVER3
     *
     * @param reserver3 the value for ONLINEQC.Y_RGQUEUETAB.RESERVER3
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setReserver3(String reserver3) {
        this.reserver3 = reserver3;
    }
}