package com.spring.model1;

public class YRgswitchtabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGSWITCHTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGSWITCHTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String destsysid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_RGSWITCHTAB.SWITCHDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String switchdbid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGSWITCHTAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_RGSWITCHTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGSWITCHTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_RGSWITCHTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGSWITCHTAB.DESTSYSID
     *
     * @return the value of ONLINEQC.Y_RGSWITCHTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getDestsysid() {
        return destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGSWITCHTAB.DESTSYSID
     *
     * @param destsysid the value for ONLINEQC.Y_RGSWITCHTAB.DESTSYSID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setDestsysid(String destsysid) {
        this.destsysid = destsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_RGSWITCHTAB.SWITCHDBID
     *
     * @return the value of ONLINEQC.Y_RGSWITCHTAB.SWITCHDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getSwitchdbid() {
        return switchdbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_RGSWITCHTAB.SWITCHDBID
     *
     * @param switchdbid the value for ONLINEQC.Y_RGSWITCHTAB.SWITCHDBID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setSwitchdbid(String switchdbid) {
        this.switchdbid = switchdbid;
    }
}