package com.spring.model1;

import java.math.BigDecimal;
import java.util.Date;

public class YSmanagertab extends YSmanagertabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.MGRNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String mgrname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.MGRJOBNUM
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String mgrjobnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.MGRSTATUS
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private BigDecimal mgrstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.MGRPASSWD
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String mgrpasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.MGRNICKNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String mgrnickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.REGISTERTIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.MGRTEL
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String mgrtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.MGREMAIL
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String mgremail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.LOGINCOUNT
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private BigDecimal logincount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.LASTLOGINADDR
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String lastloginaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.LASTLOGINTIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private Date lastlogintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMANAGERTAB.INMGR
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private BigDecimal inmgr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRNAME
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.MGRNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMgrname() {
        return mgrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRNAME
     *
     * @param mgrname the value for ONLINEQC.Y_SMANAGERTAB.MGRNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMgrname(String mgrname) {
        this.mgrname = mgrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRJOBNUM
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.MGRJOBNUM
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMgrjobnum() {
        return mgrjobnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRJOBNUM
     *
     * @param mgrjobnum the value for ONLINEQC.Y_SMANAGERTAB.MGRJOBNUM
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMgrjobnum(String mgrjobnum) {
        this.mgrjobnum = mgrjobnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRSTATUS
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.MGRSTATUS
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public BigDecimal getMgrstatus() {
        return mgrstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRSTATUS
     *
     * @param mgrstatus the value for ONLINEQC.Y_SMANAGERTAB.MGRSTATUS
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMgrstatus(BigDecimal mgrstatus) {
        this.mgrstatus = mgrstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRPASSWD
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.MGRPASSWD
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMgrpasswd() {
        return mgrpasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRPASSWD
     *
     * @param mgrpasswd the value for ONLINEQC.Y_SMANAGERTAB.MGRPASSWD
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMgrpasswd(String mgrpasswd) {
        this.mgrpasswd = mgrpasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRNICKNAME
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.MGRNICKNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMgrnickname() {
        return mgrnickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRNICKNAME
     *
     * @param mgrnickname the value for ONLINEQC.Y_SMANAGERTAB.MGRNICKNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMgrnickname(String mgrnickname) {
        this.mgrnickname = mgrnickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.REGISTERTIME
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.REGISTERTIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.REGISTERTIME
     *
     * @param registertime the value for ONLINEQC.Y_SMANAGERTAB.REGISTERTIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRTEL
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.MGRTEL
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMgrtel() {
        return mgrtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.MGRTEL
     *
     * @param mgrtel the value for ONLINEQC.Y_SMANAGERTAB.MGRTEL
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMgrtel(String mgrtel) {
        this.mgrtel = mgrtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.MGREMAIL
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.MGREMAIL
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMgremail() {
        return mgremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.MGREMAIL
     *
     * @param mgremail the value for ONLINEQC.Y_SMANAGERTAB.MGREMAIL
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMgremail(String mgremail) {
        this.mgremail = mgremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.LOGINCOUNT
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.LOGINCOUNT
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public BigDecimal getLogincount() {
        return logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.LOGINCOUNT
     *
     * @param logincount the value for ONLINEQC.Y_SMANAGERTAB.LOGINCOUNT
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setLogincount(BigDecimal logincount) {
        this.logincount = logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.LASTLOGINADDR
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.LASTLOGINADDR
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getLastloginaddr() {
        return lastloginaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.LASTLOGINADDR
     *
     * @param lastloginaddr the value for ONLINEQC.Y_SMANAGERTAB.LASTLOGINADDR
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setLastloginaddr(String lastloginaddr) {
        this.lastloginaddr = lastloginaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.LASTLOGINTIME
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.LASTLOGINTIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.LASTLOGINTIME
     *
     * @param lastlogintime the value for ONLINEQC.Y_SMANAGERTAB.LASTLOGINTIME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMANAGERTAB.INMGR
     *
     * @return the value of ONLINEQC.Y_SMANAGERTAB.INMGR
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public BigDecimal getInmgr() {
        return inmgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMANAGERTAB.INMGR
     *
     * @param inmgr the value for ONLINEQC.Y_SMANAGERTAB.INMGR
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setInmgr(BigDecimal inmgr) {
        this.inmgr = inmgr;
    }
}