package com.spring.model1;

public class YSmenuitemtab extends YSmenuitemtabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMENUITEMTAB.MENUKEY
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String menukey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMENUITEMTAB.MENUNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMENUITEMTAB.MENUDESCR
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String menudescr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMENUITEMTAB.SHOWPERMKEY
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String showpermkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMENUITEMTAB.CLICKPERMKEY
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String clickpermkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMENUITEMTAB.ICONCLASSNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String iconclassname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMENUITEMTAB.MENUURL
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String menuurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMENUITEMTAB.MENUACTIVEURLLIST
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String menuactiveurllist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SMENUITEMTAB.SORTNO
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private Long sortno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMENUITEMTAB.MENUKEY
     *
     * @return the value of ONLINEQC.Y_SMENUITEMTAB.MENUKEY
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMenukey() {
        return menukey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMENUITEMTAB.MENUKEY
     *
     * @param menukey the value for ONLINEQC.Y_SMENUITEMTAB.MENUKEY
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMenukey(String menukey) {
        this.menukey = menukey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMENUITEMTAB.MENUNAME
     *
     * @return the value of ONLINEQC.Y_SMENUITEMTAB.MENUNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMENUITEMTAB.MENUNAME
     *
     * @param menuname the value for ONLINEQC.Y_SMENUITEMTAB.MENUNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMENUITEMTAB.MENUDESCR
     *
     * @return the value of ONLINEQC.Y_SMENUITEMTAB.MENUDESCR
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMenudescr() {
        return menudescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMENUITEMTAB.MENUDESCR
     *
     * @param menudescr the value for ONLINEQC.Y_SMENUITEMTAB.MENUDESCR
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMenudescr(String menudescr) {
        this.menudescr = menudescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMENUITEMTAB.SHOWPERMKEY
     *
     * @return the value of ONLINEQC.Y_SMENUITEMTAB.SHOWPERMKEY
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getShowpermkey() {
        return showpermkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMENUITEMTAB.SHOWPERMKEY
     *
     * @param showpermkey the value for ONLINEQC.Y_SMENUITEMTAB.SHOWPERMKEY
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setShowpermkey(String showpermkey) {
        this.showpermkey = showpermkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMENUITEMTAB.CLICKPERMKEY
     *
     * @return the value of ONLINEQC.Y_SMENUITEMTAB.CLICKPERMKEY
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getClickpermkey() {
        return clickpermkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMENUITEMTAB.CLICKPERMKEY
     *
     * @param clickpermkey the value for ONLINEQC.Y_SMENUITEMTAB.CLICKPERMKEY
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setClickpermkey(String clickpermkey) {
        this.clickpermkey = clickpermkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMENUITEMTAB.ICONCLASSNAME
     *
     * @return the value of ONLINEQC.Y_SMENUITEMTAB.ICONCLASSNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getIconclassname() {
        return iconclassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMENUITEMTAB.ICONCLASSNAME
     *
     * @param iconclassname the value for ONLINEQC.Y_SMENUITEMTAB.ICONCLASSNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setIconclassname(String iconclassname) {
        this.iconclassname = iconclassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMENUITEMTAB.MENUURL
     *
     * @return the value of ONLINEQC.Y_SMENUITEMTAB.MENUURL
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMENUITEMTAB.MENUURL
     *
     * @param menuurl the value for ONLINEQC.Y_SMENUITEMTAB.MENUURL
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMENUITEMTAB.MENUACTIVEURLLIST
     *
     * @return the value of ONLINEQC.Y_SMENUITEMTAB.MENUACTIVEURLLIST
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getMenuactiveurllist() {
        return menuactiveurllist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMENUITEMTAB.MENUACTIVEURLLIST
     *
     * @param menuactiveurllist the value for ONLINEQC.Y_SMENUITEMTAB.MENUACTIVEURLLIST
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setMenuactiveurllist(String menuactiveurllist) {
        this.menuactiveurllist = menuactiveurllist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SMENUITEMTAB.SORTNO
     *
     * @return the value of ONLINEQC.Y_SMENUITEMTAB.SORTNO
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public Long getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SMENUITEMTAB.SORTNO
     *
     * @param sortno the value for ONLINEQC.Y_SMENUITEMTAB.SORTNO
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setSortno(Long sortno) {
        this.sortno = sortno;
    }
}