package com.spring.model1;

public class YSsystemstatustabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String tenantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.MODULENAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String modulename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.GROUPNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.ATTRNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    private String attrname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.TENANTID
     *
     * @return the value of ONLINEQC.Y_SSYSTEMSTATUSTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.TENANTID
     *
     * @param tenantid the value for ONLINEQC.Y_SSYSTEMSTATUSTAB.TENANTID
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.MODULENAME
     *
     * @return the value of ONLINEQC.Y_SSYSTEMSTATUSTAB.MODULENAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.MODULENAME
     *
     * @param modulename the value for ONLINEQC.Y_SSYSTEMSTATUSTAB.MODULENAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setModulename(String modulename) {
        this.modulename = modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.GROUPNAME
     *
     * @return the value of ONLINEQC.Y_SSYSTEMSTATUSTAB.GROUPNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.GROUPNAME
     *
     * @param groupname the value for ONLINEQC.Y_SSYSTEMSTATUSTAB.GROUPNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.ATTRNAME
     *
     * @return the value of ONLINEQC.Y_SSYSTEMSTATUSTAB.ATTRNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public String getAttrname() {
        return attrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINEQC.Y_SSYSTEMSTATUSTAB.ATTRNAME
     *
     * @param attrname the value for ONLINEQC.Y_SSYSTEMSTATUSTAB.ATTRNAME
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    public void setAttrname(String attrname) {
        this.attrname = attrname;
    }
}