package com.spring.dao1;

import com.spring.model1.QcPopupinfo;
import com.spring.model1.QcPopupinfoExample;
import com.spring.model1.QcPopupinfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QcPopupinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    long countByExample(QcPopupinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByExample(QcPopupinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByPrimaryKey(QcPopupinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insert(QcPopupinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insertSelective(QcPopupinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    List<QcPopupinfo> selectByExample(QcPopupinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    QcPopupinfo selectByPrimaryKey(QcPopupinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") QcPopupinfo record, @Param("example") QcPopupinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExample(@Param("record") QcPopupinfo record, @Param("example") QcPopupinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKeySelective(QcPopupinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_POPUPINFO
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKey(QcPopupinfo record);
}