package com.spring.dao1;

import com.spring.model1.QcQualitymouldtab;
import com.spring.model1.QcQualitymouldtabExample;
import com.spring.model1.QcQualitymouldtabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QcQualitymouldtabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    long countByExample(QcQualitymouldtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByExample(QcQualitymouldtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByPrimaryKey(QcQualitymouldtabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insert(QcQualitymouldtab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insertSelective(QcQualitymouldtab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    List<QcQualitymouldtab> selectByExample(QcQualitymouldtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    QcQualitymouldtab selectByPrimaryKey(QcQualitymouldtabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") QcQualitymouldtab record, @Param("example") QcQualitymouldtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExample(@Param("record") QcQualitymouldtab record, @Param("example") QcQualitymouldtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKeySelective(QcQualitymouldtab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_QUALITYMOULDTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKey(QcQualitymouldtab record);
}