package com.spring.dao1;

import com.spring.model1.QcTalkcheckprocesstab;
import com.spring.model1.QcTalkcheckprocesstabExample;
import com.spring.model1.QcTalkcheckprocesstabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QcTalkcheckprocesstabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    long countByExample(QcTalkcheckprocesstabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByExample(QcTalkcheckprocesstabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByPrimaryKey(QcTalkcheckprocesstabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insert(QcTalkcheckprocesstab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insertSelective(QcTalkcheckprocesstab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    List<QcTalkcheckprocesstab> selectByExample(QcTalkcheckprocesstabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    QcTalkcheckprocesstab selectByPrimaryKey(QcTalkcheckprocesstabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") QcTalkcheckprocesstab record, @Param("example") QcTalkcheckprocesstabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExample(@Param("record") QcTalkcheckprocesstab record, @Param("example") QcTalkcheckprocesstabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKeySelective(QcTalkcheckprocesstab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.QC_TALKCHECKPROCESSTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKey(QcTalkcheckprocesstab record);
}