package com.spring.dao1;

import com.spring.model1.YAggeneralgrouptab;
import com.spring.model1.YAggeneralgrouptabExample;
import com.spring.model1.YAggeneralgrouptabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YAggeneralgrouptabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    long countByExample(YAggeneralgrouptabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByExample(YAggeneralgrouptabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByPrimaryKey(YAggeneralgrouptabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insert(YAggeneralgrouptab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insertSelective(YAggeneralgrouptab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    List<YAggeneralgrouptab> selectByExample(YAggeneralgrouptabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    YAggeneralgrouptab selectByPrimaryKey(YAggeneralgrouptabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") YAggeneralgrouptab record, @Param("example") YAggeneralgrouptabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExample(@Param("record") YAggeneralgrouptab record, @Param("example") YAggeneralgrouptabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKeySelective(YAggeneralgrouptab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGGENERALGROUPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKey(YAggeneralgrouptab record);
}