package com.spring.dao1;

import com.spring.model1.YAgplace2dntab;
import com.spring.model1.YAgplace2dntabExample;
import com.spring.model1.YAgplace2dntabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YAgplace2dntabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    long countByExample(YAgplace2dntabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByExample(YAgplace2dntabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByPrimaryKey(YAgplace2dntabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insert(YAgplace2dntab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insertSelective(YAgplace2dntab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    List<YAgplace2dntab> selectByExample(YAgplace2dntabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    YAgplace2dntab selectByPrimaryKey(YAgplace2dntabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") YAgplace2dntab record, @Param("example") YAgplace2dntabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExample(@Param("record") YAgplace2dntab record, @Param("example") YAgplace2dntabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKeySelective(YAgplace2dntab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_AGPLACE2DNTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKey(YAgplace2dntab record);
}