package com.spring.dao1;

import com.spring.model1.YCfacetgroupobjecttab;
import com.spring.model1.YCfacetgroupobjecttabExample;
import com.spring.model1.YCfacetgroupobjecttabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YCfacetgroupobjecttabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    long countByExample(YCfacetgroupobjecttabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByExample(YCfacetgroupobjecttabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByPrimaryKey(YCfacetgroupobjecttabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insert(YCfacetgroupobjecttab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insertSelective(YCfacetgroupobjecttab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    List<YCfacetgroupobjecttab> selectByExample(YCfacetgroupobjecttabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    YCfacetgroupobjecttab selectByPrimaryKey(YCfacetgroupobjecttabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") YCfacetgroupobjecttab record, @Param("example") YCfacetgroupobjecttabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExample(@Param("record") YCfacetgroupobjecttab record, @Param("example") YCfacetgroupobjecttabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKeySelective(YCfacetgroupobjecttab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CFACETGROUPOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKey(YCfacetgroupobjecttab record);
}