package com.spring.dao1;

import com.spring.model1.YChfacetobjecttab;
import com.spring.model1.YChfacetobjecttabExample;
import com.spring.model1.YChfacetobjecttabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YChfacetobjecttabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    long countByExample(YChfacetobjecttabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByExample(YChfacetobjecttabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByPrimaryKey(YChfacetobjecttabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insert(YChfacetobjecttab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insertSelective(YChfacetobjecttab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    List<YChfacetobjecttab> selectByExample(YChfacetobjecttabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    YChfacetobjecttab selectByPrimaryKey(YChfacetobjecttabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") YChfacetobjecttab record, @Param("example") YChfacetobjecttabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExample(@Param("record") YChfacetobjecttab record, @Param("example") YChfacetobjecttabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKeySelective(YChfacetobjecttab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CHFACETOBJECTTAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKey(YChfacetobjecttab record);
}