package com.spring.dao1;

import com.spring.model1.YCindexthresholdyeartab0;
import com.spring.model1.YCindexthresholdyeartab0Example;
import com.spring.model1.YCindexthresholdyeartab0Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YCindexthresholdyeartab0Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    long countByExample(YCindexthresholdyeartab0Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByExample(YCindexthresholdyeartab0Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByPrimaryKey(YCindexthresholdyeartab0Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insert(YCindexthresholdyeartab0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insertSelective(YCindexthresholdyeartab0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    List<YCindexthresholdyeartab0> selectByExample(YCindexthresholdyeartab0Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    YCindexthresholdyeartab0 selectByPrimaryKey(YCindexthresholdyeartab0Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") YCindexthresholdyeartab0 record, @Param("example") YCindexthresholdyeartab0Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExample(@Param("record") YCindexthresholdyeartab0 record, @Param("example") YCindexthresholdyeartab0Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKeySelective(YCindexthresholdyeartab0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTHRESHOLDYEARTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKey(YCindexthresholdyeartab0 record);
}