package com.spring.dao1;

import com.spring.model1.YCindextargetdaytab0;
import com.spring.model1.YCindextargetdaytab0Example;
import com.spring.model1.YCindextargetdaytab0Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YCindextargetdaytab0Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    long countByExample(YCindextargetdaytab0Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int deleteByExample(YCindextargetdaytab0Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int deleteByPrimaryKey(YCindextargetdaytab0Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int insert(YCindextargetdaytab0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int insertSelective(YCindextargetdaytab0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    List<YCindextargetdaytab0> selectByExample(YCindextargetdaytab0Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    YCindextargetdaytab0 selectByPrimaryKey(YCindextargetdaytab0Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") YCindextargetdaytab0 record, @Param("example") YCindextargetdaytab0Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByExample(@Param("record") YCindextargetdaytab0 record, @Param("example") YCindextargetdaytab0Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByPrimaryKeySelective(YCindextargetdaytab0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_CINDEXTARGETDAYTAB0
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByPrimaryKey(YCindextargetdaytab0 record);
}