package com.spring.dao1;

import com.spring.model1.YDestsysmappingbuslinetab;
import com.spring.model1.YDestsysmappingbuslinetabExample;
import com.spring.model1.YDestsysmappingbuslinetabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YDestsysmappingbuslinetabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    long countByExample(YDestsysmappingbuslinetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByExample(YDestsysmappingbuslinetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByPrimaryKey(YDestsysmappingbuslinetabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insert(YDestsysmappingbuslinetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insertSelective(YDestsysmappingbuslinetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    List<YDestsysmappingbuslinetab> selectByExample(YDestsysmappingbuslinetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    YDestsysmappingbuslinetab selectByPrimaryKey(YDestsysmappingbuslinetabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") YDestsysmappingbuslinetab record, @Param("example") YDestsysmappingbuslinetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExample(@Param("record") YDestsysmappingbuslinetab record, @Param("example") YDestsysmappingbuslinetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKeySelective(YDestsysmappingbuslinetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DESTSYSMAPPINGBUSLINETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKey(YDestsysmappingbuslinetab record);
}