package com.spring.dao1;

import com.spring.model1.YDgagentoptvaluetab;
import com.spring.model1.YDgagentoptvaluetabExample;
import com.spring.model1.YDgagentoptvaluetabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YDgagentoptvaluetabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    long countByExample(YDgagentoptvaluetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByExample(YDgagentoptvaluetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int deleteByPrimaryKey(YDgagentoptvaluetabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insert(YDgagentoptvaluetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int insertSelective(YDgagentoptvaluetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    List<YDgagentoptvaluetab> selectByExample(YDgagentoptvaluetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    YDgagentoptvaluetab selectByPrimaryKey(YDgagentoptvaluetabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") YDgagentoptvaluetab record, @Param("example") YDgagentoptvaluetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByExample(@Param("record") YDgagentoptvaluetab record, @Param("example") YDgagentoptvaluetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKeySelective(YDgagentoptvaluetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_DGAGENTOPTVALUETAB
     *
     * @mbg.generated Tue Jan 08 16:40:05 CST 2019
     */
    int updateByPrimaryKey(YDgagentoptvaluetab record);
}