package com.spring.dao1;

import com.spring.model1.YHvfactormonthtab3;
import com.spring.model1.YHvfactormonthtab3Example;
import com.spring.model1.YHvfactormonthtab3Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YHvfactormonthtab3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:06 CST 2019
     */
    long countByExample(YHvfactormonthtab3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:06 CST 2019
     */
    int deleteByExample(YHvfactormonthtab3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:06 CST 2019
     */
    int deleteByPrimaryKey(YHvfactormonthtab3Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:06 CST 2019
     */
    int insert(YHvfactormonthtab3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:06 CST 2019
     */
    int insertSelective(YHvfactormonthtab3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:06 CST 2019
     */
    List<YHvfactormonthtab3> selectByExample(YHvfactormonthtab3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:06 CST 2019
     */
    YHvfactormonthtab3 selectByPrimaryKey(YHvfactormonthtab3Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") YHvfactormonthtab3 record, @Param("example") YHvfactormonthtab3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:06 CST 2019
     */
    int updateByExample(@Param("record") YHvfactormonthtab3 record, @Param("example") YHvfactormonthtab3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:06 CST 2019
     */
    int updateByPrimaryKeySelective(YHvfactormonthtab3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_HVFACTORMONTHTAB3
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int updateByPrimaryKey(YHvfactormonthtab3 record);
}