package com.spring.dao1;

import com.spring.model1.YIndexdataimptab;
import com.spring.model1.YIndexdataimptabExample;
import com.spring.model1.YIndexdataimptabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YIndexdataimptabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    long countByExample(YIndexdataimptabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int deleteByExample(YIndexdataimptabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int deleteByPrimaryKey(YIndexdataimptabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int insert(YIndexdataimptab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int insertSelective(YIndexdataimptab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    List<YIndexdataimptab> selectByExample(YIndexdataimptabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    YIndexdataimptab selectByPrimaryKey(YIndexdataimptabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") YIndexdataimptab record, @Param("example") YIndexdataimptabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByExample(@Param("record") YIndexdataimptab record, @Param("example") YIndexdataimptabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByPrimaryKeySelective(YIndexdataimptab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_INDEXDATAIMPTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByPrimaryKey(YIndexdataimptab record);
}