package com.spring.dao1;

import com.spring.model1.YMdirectorstatusinfotab;
import com.spring.model1.YMdirectorstatusinfotabExample;
import com.spring.model1.YMdirectorstatusinfotabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YMdirectorstatusinfotabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    long countByExample(YMdirectorstatusinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByExample(YMdirectorstatusinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByPrimaryKey(YMdirectorstatusinfotabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insert(YMdirectorstatusinfotab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insertSelective(YMdirectorstatusinfotab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    List<YMdirectorstatusinfotab> selectByExample(YMdirectorstatusinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    YMdirectorstatusinfotab selectByPrimaryKey(YMdirectorstatusinfotabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") YMdirectorstatusinfotab record, @Param("example") YMdirectorstatusinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExample(@Param("record") YMdirectorstatusinfotab record, @Param("example") YMdirectorstatusinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKeySelective(YMdirectorstatusinfotab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKey(YMdirectorstatusinfotab record);
}