package com.spring.dao1;

import com.spring.model1.YMdirectorresponsetab;
import com.spring.model1.YMdirectorresponsetabExample;
import com.spring.model1.YMdirectorresponsetabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YMdirectorresponsetabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    long countByExample(YMdirectorresponsetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByExample(YMdirectorresponsetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByPrimaryKey(YMdirectorresponsetabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insert(YMdirectorresponsetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insertSelective(YMdirectorresponsetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    List<YMdirectorresponsetab> selectByExample(YMdirectorresponsetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    YMdirectorresponsetab selectByPrimaryKey(YMdirectorresponsetabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") YMdirectorresponsetab record, @Param("example") YMdirectorresponsetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExample(@Param("record") YMdirectorresponsetab record, @Param("example") YMdirectorresponsetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKeySelective(YMdirectorresponsetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORRESPONSETAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKey(YMdirectorresponsetab record);
}