package com.spring.dao1;

import com.spring.model1.YMdirectorstatuschangeinfotab;
import com.spring.model1.YMdirectorstatuschangeinfotabExample;
import com.spring.model1.YMdirectorstatuschangeinfotabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YMdirectorstatuschangeinfotabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    long countByExample(YMdirectorstatuschangeinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByExample(YMdirectorstatuschangeinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByPrimaryKey(YMdirectorstatuschangeinfotabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insert(YMdirectorstatuschangeinfotab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insertSelective(YMdirectorstatuschangeinfotab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    List<YMdirectorstatuschangeinfotab> selectByExample(YMdirectorstatuschangeinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    YMdirectorstatuschangeinfotab selectByPrimaryKey(YMdirectorstatuschangeinfotabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") YMdirectorstatuschangeinfotab record, @Param("example") YMdirectorstatuschangeinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExample(@Param("record") YMdirectorstatuschangeinfotab record, @Param("example") YMdirectorstatuschangeinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKeySelective(YMdirectorstatuschangeinfotab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MDIRECTORSTATUSCHANGEINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKey(YMdirectorstatuschangeinfotab record);
}