package com.spring.dao1;

import com.spring.model1.YMfactorattrtab;
import com.spring.model1.YMfactorattrtabExample;
import com.spring.model1.YMfactorattrtabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YMfactorattrtabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    long countByExample(YMfactorattrtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int deleteByExample(YMfactorattrtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int deleteByPrimaryKey(YMfactorattrtabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int insert(YMfactorattrtab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int insertSelective(YMfactorattrtab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    List<YMfactorattrtab> selectByExample(YMfactorattrtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    YMfactorattrtab selectByPrimaryKey(YMfactorattrtabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") YMfactorattrtab record, @Param("example") YMfactorattrtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int updateByExample(@Param("record") YMfactorattrtab record, @Param("example") YMfactorattrtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int updateByPrimaryKeySelective(YMfactorattrtab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MFACTORATTRTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int updateByPrimaryKey(YMfactorattrtab record);
}