package com.spring.dao1;

import com.spring.model1.YMseatinfotab;
import com.spring.model1.YMseatinfotabExample;
import com.spring.model1.YMseatinfotabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YMseatinfotabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    long countByExample(YMseatinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByExample(YMseatinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByPrimaryKey(YMseatinfotabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insert(YMseatinfotab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insertSelective(YMseatinfotab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    List<YMseatinfotab> selectByExample(YMseatinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    YMseatinfotab selectByPrimaryKey(YMseatinfotabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") YMseatinfotab record, @Param("example") YMseatinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExample(@Param("record") YMseatinfotab record, @Param("example") YMseatinfotabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKeySelective(YMseatinfotab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_MSEATINFOTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKey(YMseatinfotab record);
}