package com.spring.dao1;

import com.spring.model1.YRgagentgroup2persontab;
import com.spring.model1.YRgagentgroup2persontabExample;
import com.spring.model1.YRgagentgroup2persontabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YRgagentgroup2persontabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    long countByExample(YRgagentgroup2persontabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int deleteByExample(YRgagentgroup2persontabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int deleteByPrimaryKey(YRgagentgroup2persontabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int insert(YRgagentgroup2persontab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int insertSelective(YRgagentgroup2persontab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    List<YRgagentgroup2persontab> selectByExample(YRgagentgroup2persontabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    YRgagentgroup2persontab selectByPrimaryKey(YRgagentgroup2persontabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") YRgagentgroup2persontab record, @Param("example") YRgagentgroup2persontabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByExample(@Param("record") YRgagentgroup2persontab record, @Param("example") YRgagentgroup2persontabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByPrimaryKeySelective(YRgagentgroup2persontab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_RGAGENTGROUP2PERSONTAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByPrimaryKey(YRgagentgroup2persontab record);
}