package com.spring.dao1;

import com.spring.model1.YScenestatusalarmindexobjtab;
import com.spring.model1.YScenestatusalarmindexobjtabExample;
import com.spring.model1.YScenestatusalarmindexobjtabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YScenestatusalarmindexobjtabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    long countByExample(YScenestatusalarmindexobjtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByExample(YScenestatusalarmindexobjtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int deleteByPrimaryKey(YScenestatusalarmindexobjtabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insert(YScenestatusalarmindexobjtab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int insertSelective(YScenestatusalarmindexobjtab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    List<YScenestatusalarmindexobjtab> selectByExample(YScenestatusalarmindexobjtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    YScenestatusalarmindexobjtab selectByPrimaryKey(YScenestatusalarmindexobjtabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") YScenestatusalarmindexobjtab record, @Param("example") YScenestatusalarmindexobjtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByExample(@Param("record") YScenestatusalarmindexobjtab record, @Param("example") YScenestatusalarmindexobjtabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKeySelective(YScenestatusalarmindexobjtab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SCENESTATUSALARMINDEXOBJTAB
     *
     * @mbg.generated Tue Jan 08 16:40:10 CST 2019
     */
    int updateByPrimaryKey(YScenestatusalarmindexobjtab record);
}