package com.spring.dao1;

import com.spring.model1.YShmanagerfacetab;
import com.spring.model1.YShmanagerfacetabExample;
import com.spring.model1.YShmanagerfacetabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YShmanagerfacetabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    long countByExample(YShmanagerfacetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int deleteByExample(YShmanagerfacetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int deleteByPrimaryKey(YShmanagerfacetabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int insert(YShmanagerfacetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int insertSelective(YShmanagerfacetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    List<YShmanagerfacetab> selectByExample(YShmanagerfacetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    YShmanagerfacetab selectByPrimaryKey(YShmanagerfacetabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") YShmanagerfacetab record, @Param("example") YShmanagerfacetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByExample(@Param("record") YShmanagerfacetab record, @Param("example") YShmanagerfacetabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByPrimaryKeySelective(YShmanagerfacetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SHMANAGERFACETAB
     *
     * @mbg.generated Tue Jan 08 16:40:09 CST 2019
     */
    int updateByPrimaryKey(YShmanagerfacetab record);
}