package com.spring.dao1;

import com.spring.model1.YSystemdictab;
import com.spring.model1.YSystemdictabExample;
import com.spring.model1.YSystemdictabKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YSystemdictabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    long countByExample(YSystemdictabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int deleteByExample(YSystemdictabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int deleteByPrimaryKey(YSystemdictabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int insert(YSystemdictab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int insertSelective(YSystemdictab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    List<YSystemdictab> selectByExample(YSystemdictabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    YSystemdictab selectByPrimaryKey(YSystemdictabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") YSystemdictab record, @Param("example") YSystemdictabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int updateByExample(@Param("record") YSystemdictab record, @Param("example") YSystemdictabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int updateByPrimaryKeySelective(YSystemdictab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINEQC.Y_SYSTEMDICTAB
     *
     * @mbg.generated Tue Jan 08 16:40:07 CST 2019
     */
    int updateByPrimaryKey(YSystemdictab record);
}